In [141]:
import requests

In [142]:
URL = "https://rabota.by/search/vacancy"

In [143]:
params = {
    "text": "Data Scientist"
}

In [144]:
headers = {
    "User-Agent": "DataCareerMap/1.0 educational research"
}
response = requests.get(
    URL,
    params=params,
    headers=headers,
    timeout=20
)

In [145]:
print(response.status_code)
print(response.url)
print(response.headers.get("Content-Type"))

200
https://rabota.by/search/vacancy?text=Data+Scientist
text/html; charset=utf-8

In [146]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(
    response.text,
    "html.parser"
)

In [147]:
soup

<!DOCTYPE html>

<html class="desktop" lang="ru">
<!-- request: 1787054774443ff99f92dc4fe40c2008 -->
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<title data-rh="">Работа в Минске, свежие вакансии - rabota.by</title>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Найти работу в Минске! ★ rabota.by - свежие вакансии в Минске от прямых работодателей в 28 профобластях. Поиск работы и сотрудников на rabota.by." data-rh="" name="description"/>
<meta content="Работа в Минске, свежие вакансии - rabota.by" data-rh="" property="og:title"/><meta content="Найти работу в Минске! ★ rabota.by - свежие вакансии в Минске от прямых работодателей в 28 профобластях. Поиск работы и сотрудников на rabota.by." data-rh="" property="og:description"/><meta content="https://i.rabota.by/images/logos/openGraph/rabota.by.png?v=29012024" data-rh="" property="og:image"/><meta content="600" data-rh="" property="og:image:width"/><meta content="315" data-rh="" property="og:image:height"/>
<meta content="04e999be295c4789b47d48316566353e-b31cf1577fb869fe-0" name="sentry-trace"/>
<meta content="sentry-trace_id=04e999be295c4789b47d48316566353e,sentry-sample_rand=0.017843,sentry-environment=production,sentry-release=xhh%4026.34.2.1,sentry-public_key=0cc3a09b6698423b8ca47d3478cfccac,sentry-transaction=/search/vacancy,sentry-sample_rate=0.001,sentry-sampled=false" name="baggage"/>
<script id="js-script-global-vars" nonce="">
window.bloko = {
    fontUrl: 'https://i.rabota.by/styles/other/pages/__fonts_3e2a20dec491e4294c7ec1c4f92c6567.css'
};
window.magritte = {
    fontUrl: 'https://i.rabota.by/styles/other/pages/__magritte-fonts_4d0d9a933ed53bff79307aad380085e8.css'
};
window.globalVars = {"ads_sandbox": 0, "analyticsParams": {"hhtmFrom": "", "hhtmFromLabel": "", "hhtmSource": "vacancy_search_list", "hhtmSourceLabel": "", "screenType": "SIMPLE"}, "apiHost": "https://api.hh.ru", "apiXhhHost": "https://rabota.by", "area": "16", "autotestsComponentsInitEnd": false, "build": "26.34.2.1", "buildFolder": "build", "countersDisabled": true, "country": "4", "cryptedUserId": "", "cssMaping": {"applicant-applicant": {"dir": "applicant", "name": "applicant", "path": "styles/applicant/pages/__applicant_96f3d951b748fce864ffa4da258f1834.css"}, "components-common": {"dir": "components-common", "name": "components-common", "path": "build/components-common.7807361c0bc48666.css"}, "employer-employer": {"dir": "employer", "name": "employer", "path": "styles/employer/pages/__employer_b6688e3d52fcaf8e1cb55cd39f6cee46.css"}, "globals-account": {"dir": "globals", "name": "account", "path": "styles/globals/pages/__account_6bd53cd27c7d9936e396ec27aee61f38.css"}, "globals-bloko-imports": {"dir": "globals", "name": "bloko-imports", "path": "styles/globals/pages/__bloko-imports_e3098b35d51f1eb2346ce8dc65cb1dfc.css"}, "globals-bloko-overrides": {"dir": "globals", "name": "bloko-overrides", "path": "styles/globals/pages/__bloko-overrides_3d5b021e4cc395ea6259b6c94c3e4bdf.css"}, "globals-globals": {"dir": "globals", "name": "globals", "path": "styles/globals/pages/__globals_bff7f564570a1bdcd6f0004f1cffabe2.css"}, "magritte": {"dir": "magritte", "name": "magritte", "path": "build/magritte.e053046ad4c49438.css"}, "other-ckeditor": {"dir": "other", "name": "ckeditor", "path": "styles/other/pages/__ckeditor_25bc7f0dd460705f42468629887f9257.css"}, "other-fonts": {"dir": "other", "name": "fonts", "path": "styles/other/pages/__fonts_3e2a20dec491e4294c7ec1c4f92c6567.css"}, "other-magritte-fonts": {"dir": "other", "name": "magritte-fonts", "path": "styles/other/pages/__magritte-fonts_4d0d9a933ed53bff79307aad380085e8.css"}, "vendors": {"dir": "vendors", "name": "vendors", "path": "build/vendors.98871fc37c5f125f.css"}}, "employerState": "", "features": {"Inter_font_enabled": null, "add_hhtm_to_link_href": null, "anonymous_resume_enabled": null, "chat_write_possibility_controls_enabled": null, "disable_app_init_for_ie11": null, "disable_counters": false, "employer_chrome_extensions_to_detect": "[\n  {\n    \"name\": \"spodbor\",\n    \"url\": \"chrome-extension://gafchcnohalkhohnedifhjblhdhoppkg/content.css\"\n  },\n  {\n    \"name\": \"friendwork\",\n    \"url\": \"chrome-extension://lmajkdcdknelgehdmcldckonhndcodco/fonts/Lato/lato.css\"\n  }\n]\n", "employer_extensions_to_detect": "{\"vera\": \"veraBar\", \"friendwork\": \"fwi-popup\", \"potok\": \"potok_io__chrome_extension_iframe\", \"extrasaur\": \"custom-table-iframe-div\", \"cleverStaffLogin\": \"cleverStaffNeedLogin\", \"cleverStaff\": \"cleverStaffBlock\", \"amoCRM\": \"amocrm-scrapper\", \"amoCRM2\": \"js-amo-field-mark-positioned\", \"basecheck\": \"noty_layout__topRight\", \"leo\": \"dataLeo\", \"hrDrive\": \"hh-widget-wrapper\"}", "fingerprinting_enable": true, "fingerprinting_for_anonymous_user_enable": false, "front_validation_for_password_changing": true, "get_page_html_timeout_ms": 3000, "iframe_fix_size_banners": null, "is_global_id_enabled_in_gib_fp": null, "legacy_page_react_header_split_by_hhuid": null, "live_reload": null, "secure_portal_enabled": true, "secure_portal_test_version_enabled": false, "sentry_js_config": "{\n  \"ignorePaths\": {\n    \"regexps\": [\n      \"[\\\\da-f]+/[\\\\da-f-]+/main\\\\.js\",\n      \".*akamaihd\\\\.net.+$\",\n      \"\\\\/inj_js\\\\/common\\\\.js\",\n      \"fingerprintjs\",\n      \"ckeditor4.5\",\n      \"[\\\\d\\\\.]+\\\\/combine.js\",\n      \"ckeditor/ckeditor\\\\.js\",\n      \"axios\\\\/lib\\\\/core\\\\/createError\",\n      \"fbevents\\\\.js\",\n      \"core-js\\\\/modules\\\\/es\\\\.promise\\\\.js\",\n      \"\\\\/ru_RU\\\\/all.js\",\n      \"raphael\",\n      \"/gpt/pubads_impl\",\n      \"Invalid character: \u0027\\\\0\u0027\",\n      \"roxot\",\n      \"moz-extension:\\\\/\\\\/\",\n      \"sovetnik.min.js\",\n      \"safeframe-bundles\",\n      \"\\\\/static\\\\/sync-loader\\\\.js\",\n      \"bundles-es2017\",\n      \"js\\\\/code\",\n      \"partner-code-bundles\",\n      \"\\\\/wrapper\\\\/js\\\\/common-engine\\\\.js\",\n      \"\\\\/partner-code-bundles\\\\/\",\n      \"safari-extension:\\\\/\\\\/\",\n      \"chrome:\\\\/\\\\/internal-\",\n      \"chrome-extension\",\n      \"instant-web\",\n      \"\\\\/3\\\\/zp\\\\.js\"\n    ]\n  },\n  \"ignoreErrors\": {\n    \"strings\": [\n      \"Abnormal number of requests: /shards/employer/last_search/remove\",\n      \"Abnormal number of requests: /shards/vacancy/register_interaction\",\n      \"Unhandled resource-load promise rejection\",\n      \"Event `Event` (type=error) captured as promise rejection\",\n      \"Loading CSS chunk\",\n      \"Cannot read property \u0027disguiseToken\u0027 of undefined\",\n      \"Cannot redefine property: googletag\",\n      \"Database deleted by request of the user\",\n      \"InternalError: Promise rejection value is a non-unwrappable cross-compartment wrapper.\",\n      \"Failed to update a ServiceWorker: An unknown error occurred when fetching the script.\",\n      \"\u0027e.data.indexOf\u0027 is not a function\",\n      \"Load timeout for modules:\",\n      \"__gCrWeb.autofill.extractForms\",\n      \"HTML Parsing Error: Unable to modify the parent container element before the child element is closed\",\n      \"Failed to retrieve hasPrivateToken response. Exceeded the number-of-issuers limit.\",\n      \"Failed to retrieve hasPrivateToken response.\",\n      \"Uncaught exception: TypeError: Cannot convert \u0027d.body\u0027 to object\",\n      \"Node cannot be inserted at the specified point in the hierarchy\",\n      \"TypeError: \u041d\u0435\u0434\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0439 \u0432\u044b\u0437\u044b\u0432\u0430\u044e\u0449\u0438\u0439 \u043e\u0431\u044a\u0435\u043a\u0442\",\n      \"TypeError: Load failed\",\n      \"TypeError: Failed to fetch\",\n      \"TypeError: Invalid calling object\",\n      \"TypeError: \u0027undefined\u0027 is not an object (evaluating \u0027doc.forms\u0027)\",\n      \"TypeError: Cannot read property \u0027precision\u0027 of undefined\",\n      \"The operation was aborted due to shutdown.\",\n      \"Uncaught exception: TypeError: Cannot convert \u0027a.mini\u0027 to object\",\n      \"window.zAdv\",\n      \"backbone in Function.e.Router [as extend]\",\n      \"this._doc.documentElement\",\n      \"Can\u0027t find variable: inf\",\n      \"SkypeClick2Call\",\n      \"\u0421\u0438\u043d\u0442\u0430\u043a\u0441\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u043e\u0448\u0438\u0431\u043a\u0430\",\n      \"Invalid or unexpected token\",\n      \"Unexpected token \u003c\",\n      \"Blocked a frame with origin\",\n      \"__show__deepen\",\n      \"expected expression, got \u0027\u003c\u0027\",\n      \"Cannot read property \u0027forms\u0027 of undefined\",\n      \"GM_addStyle is not defined\",\n      \"can\u0027t redefine non-configurable property \\\"userAgent\\\"\",\n      \"Can\u0027t find varfiable: auto\",\n      \"only one instance of babel-polyfill is allowed\",\n      \"this.matches is not a function\",\n      \"NS_ERROR_NOT_INITIALIZED\",\n      \"NS_ERROR_UNEXPECTED\",\n      \"jQuery(...).size is not a function\",\n      \"Unexpected token ILLEGAL\",\n      \"Unexpected identifier\",\n      \"Unexpected end of input\",\n      \"yndx_svtn_e\",\n      \"Failed to update a ServiceWorker: The script resource is behind a redirect, which is disallowed.\",\n      \"TypeError: Cannot set property \u0027destroySlots\u0027 of undefined\",\n      \"Non-Error exception captured with keys: status, statusText\",\n      \"Non-Error promise rejection captured with value: Timeout\",\n      \"Non-Error promise rejection captured with value: undefined\",\n      \"SyntaxError: The string did not match the expected pattern.\",\n      \"The operation is insecure\",\n      \"No identifiers allowed directly after numeric literal\",\n      \"wmrzz_time2 is not defined\",\n      \"Request failed with status code 403\",\n      \"Request failed with status code 502\",\n      \"SYNTAX_ERR: DOM Exception 12\",\n      \"Unexpected end of script\",\n      \"maxthon\",\n      \"Request aborted\",\n      \"play() failed because the user didn\u0027t interact with the document first\",\n      \"NetworkError when attempting to fetch resource.\",\n      \"The operation was aborted.\",\n      \"wmrzz_zakrit2\",\n      \"l.LegacyGlobal.should_do_lastpass_here\",\n      \"measurePositions is not defined\",\n      \"JSON syntax error\",\n      \"Unexpected token \u0027else\u0027\",\n      \"Unexpected token \u0027\u003c\u0027\",\n      \"_toConsumableArray is not defined\",\n      \"GM_addStyle\",\n      \"Illegal invocation\",\n      \"ResizeObserver loop limit exceeded\",\n      \"Identifier \u0027originalPrompt\u0027 has already been declared\",\n      \"Identifier \u0027nativeIframe\u0027 has already been declared\",\n      \"UnhandledRejection: {}\",\n      \"UnhandledRejection: 5\",\n      \"ReferenceError: ServiceWorkerRegistration is not defined\",\n      \"topMsg is not defined\",\n      \"SyntaxError: illegal character U+009E\",\n      \"ResizeObserver loop completed with undelivered notifications\",\n      \"injected_main is not defined\",\n      \"Document is not focused.\",\n      \"__firefox__.favicons.getFavicons\",\n      \"Failed to get the interest cohort:\",\n      \"__VUE_DEVTOOLS_IFRAME__\",\n      \"_AutofillCallbackHandler\",\n      \"SyntaxError: Unexpected EOF\",\n      \"NotFoundError: NotFoundError\",\n      \"Ethereum is not initialized\",\n      \"document.getElementsByTagName(\u0027video\u0027)[0].webkitExitFullScreen\",\n      \"null is not an object (evaluating \u0027document.querySelector(\u0027title\u0027).textContent\u0027)\",\n      \"Cannot redefine property: src\",\n      \"Non-Error promise rejection captured with value: null\",\n      \"AbortError: The user aborted a request\",\n      \"cadesplugin is not defined\",\n      \"Cannot read properties of undefined (reading \u0027firefoxSample\u0027)\",\n      \"Non-Error promise rejection captured with value: 404\",\n      \"Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.\",\n      \"Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.\",\n      \"Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.\",\n      \"\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043f\u043e\u043b\u0443\u0447\u0438\u0442\u044c DOM-\u044d\u043b\u0435\u043c\u0435\u043d\u0442\u044b \u043a\u043d\u043e\u043f\u043e\u043a \u0441 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f\u043c\u0438. (Amo-Samokat)\",\n      \"Java object is gone\",\n      \"Failed to execute \u0027removeChild\u0027 on \u0027Node\u0027: The node to be removed is not a child of this node.\",\n      \"Java bridge method invocation error\",\n      \"UnknownError: Internal error.\",\n      \"InvalidStateError: the execution context does not exist\",\n      \"UnknownError: Connection to Indexed Database server lost. Refresh the page to try again\",\n      \"Can\u0027t find variable: gmo\",\n      \"timeout exceeded\",\n      \"Non-Error promise rejection captured with value: 0\",\n      \"Error invoking post: Method not found\",\n      \"Error invoking postEvent: Method not found\",\n      \"Request failed with status code 504\",\n      \"Request failed with status code 503\",\n      \"ReferenceError: a0_0x3b27 is not defined\"\n    ],\n    \"regexps\": [\n      \"^\\\"500 \\\"\",\n      \"^\\\"0 \\\"\",\n      \"^{}\",\n      \"^undefined$\",\n      \"^Syntax error$\",\n      \"^\u041d\u0435\u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043d\u0430\u044f \u043e\u0448\u0438\u0431\u043a\u0430\\\\.$\",\n      \"^\u041d\u0435\u0434\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0439 \u0437\u043d\u0430\u043a$\",\n      \"^TypeError undefined is not an object \\\\(evaluating \u0027a\\\\.ajax\u0027\\\\)$\",\n      \"^SyntaxError missing \\\\) after argument list$\",\n      \"^\\\\[object Event\\\\]$\",\n      \"\\\\bgST\\\\b\",\n      \"pixelPositionVal\",\n      \"boxSizingReliable\",\n      \"reliableMarginLeft\",\n      \"^\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u043f\u0430\u043c\u044f\u0442\u0438 \u0434\u043b\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438.\",\n      \"\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u043f\u0430\u043c\u044f\u0442\u0438 \u0434\u043b\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438[\\\\s\\\\S]+?fingerprint2\",\n      \"^illegal character$\",\n      \"^Access is denied\\\\.\\\\s*$\",\n      \"^Timeout$\",\n      \"^Unexpected token else$\",\n      \"^Error: 7$\",\n      \"^7$\",\n      \"^\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u043f\u0430\u043c\u044f\u0442\u0438$\",\n      \"^\\\\[CKEDITOR.resourceManager.load\\\\] Resource name \\\"default\\\" was not found at\",\n      \"can\u0027t redefine non-configurable property \\\"AceScript\\\"\",\n      \"\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u044f \u0431\u044b\u043b\u0430 \u043e\u0442\u043c\u0435\u043d\u0435\u043d\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u043c.\",\n      \"out of memory\",\n      \"Network Error\",\n      \"NetworkError\",\n      \"LegacyGlobal\",\n      \"Loading chunk\",\n      \"^No error message$\",\n      \"^\\\"Timeout\\\"$\",\n      \"^Invalid character\",\n      \"^\\\"Event\\\"$\",\n      \"^\\\"\\\\*\\\\*non-serializable\\\\*\\\\*\\\"$\",\n      \"^chrome is not defined$\",\n      \"missing \\\\) after argument list$\",\n      \"\\\"error\\\" called on an object that does not implement interface Console\",\n      \"SyntaxError: Identifier \u0027_0[xX][0-9a-fA-F]{4}\u0027 has already been declared\",\n      \"adfox#checkContainer: Element with id #roxotAd-[a-zA-Z0-9-]* not found\",\n      \"javaEnabled is not a function\",\n      \"property \u0027javaEnabled\u0027 is a read-only\",\n      \"u.remoteFrameRegistration.processChildFrameMessage\",\n      \"instantSearchSDKJSBridgeClearHighlight\",\n      \"window\\\\.cb\\\\d+\",\n      \"Object Not Found Matching Id:\\\\d+\",\n      \"metrika\\/watch.js\",\n      \"ReferenceError: Can\u0027t find variable: PaymentAutofillConfig\",\n      \"firefoxSample\",\n      \"AbortError\",\n      \"QuotaExceededError\",\n      \"indexedDB.open\",\n      \"Unable to open database file on disk\",\n      \"Internal error when calculating storage usage\",\n      \"\\\\[ Federation Runtime \\\\]: remoteEntryExports is undefined\",\n      \"\\\\[loadRemoteSharedXHH\\\\] Failed to load remote module\"\n    ],\n    \"serialize\": [{\"code\": \"4001\"}, {\"code\": \"4900\"}],\n    \"stacktraces\": [\n      \"XMLHttpRequest.request.onreadystatechange(\u003canonymous\u003e)\",\n      \"XMLHttpRequest.xhr.onreadystatechange(\u003canonymous\u003e)\",\n      \"_logEvaluatedStringInfo(\u003canonymous\u003e)\",\n      \"checkPerfReady(\u003canonymous\u003e)\",\n      \"(\u003cfront-maps-static\u003e)\",\n      \"(\u003c/metrika/tag.js\u003e)\",\n      \"(\u003c/metrika/watch.js\u003e)\",\n      \"Touch.get(\u003canonymous\u003e)\",\n      \"(\u003cblob:https:\u003e)\"\n    ]\n  },\n  \"replaysOnErrorSampleRate\": 0.12,\n  \"tracesSampleRate\": 0.00001\n}", "sentry_logging": true, "sentry_request_queue_limit": 6, "stat_shard_request_percent": false, "store_debug": false, "web_performance_analytics_percent": true, "yandex_adfox_enabled": "{ \"hh.ru\": true, \"zp.ru\": true, \"rb.by\": true, \"hh.ua\": false, \"hh.uz\": true, \"hh.ge\": true, \"hh.kg\": true, \"hh.kz\": true, \"hh.az\": true }", "ymaps_api_key": null, "ymaps_suggest_api_key": null}, "hhcdnHost": "https://hhcdn.ru", "hhid": "", "imageResizingCdnHost": "https://img.hhcdn.ru", "isWebView": false, "lang": "RU", "locale": "ru_RU", "login": "", "luxEnabled": true, "luxPageName": "VacancySearch", "microFrontends": {}, "nonce": "", "pageName": "vacancy_search_list", "requestId": "1787054774443ff99f92dc4fe40c2008", "sentryDSN": "https://55d08dbf26984dd4b9206c097b9cc2ab@sentry.hh.ru/607", "sentryExtraData": {}, "sharedRemoteEntry": "https://i.rabota.by/shared/remote.xhhshared.ba90a823c98b101e.js", "siteId": "17", "skillazURL": "https://hh.skillaz.ru", "staticHost": "https://i.rabota.by", "statsPageName": "", "timeStamp": "1787054775", "topLevelDomain": "rabota.by", "userType": "anonymous", "variables": {"appEntryPoint": "/build/appEntryPoint.5010dafeb7aa7421.js", "bloko": "/build/bloko.f88169a152cbf1f0.js", "components-common-js": "/build/components-common-js.cbe9c3cb39cda294.js", "magritte": "/build/magritte.581526ac60d85ada.js", "runtime": "/build/runtime.3ddfffc3e737b582.js", "vendors": "/build/vendors.774ca12b2830f25d.js"}};

try {
    if (typeof window.globalVars.analyticsParams === 'string') {
        window.globalVars.analyticsParams = JSON.parse(window.globalVars.analyticsParams)
    }
} catch(e) {}
</script>
<script id="js-script-inline" nonce="">

In [148]:
print(soup.title)

<title data-rh="">Работа в Минске, свежие вакансии - rabota.by</title>

In [149]:
page_text = soup.get_text(
    " ",
    strip=True
)
page_text

'Работа в Минске, свежие вакансии - rabota.by Для работы с нашим сайтом необходимо, чтобы Вы включили JavaScript в вашем браузере. Ищу работу Ищу\xa0работу Ищу\xa0работу Ищу\xa0сотрудника Ищу\xa0работу Ищу\xa0сотрудника Сервисы Помощь Ещё Поиск Минск Войти Войти Создать резюме Data Scientist Регион График Рабочие часы Опыт Тип занятости Уровень дохода Ещё фильтры Найдено 264 вакансии «Data Scientist» Data Scientist Опыт 1-3 года Ventra Москва Откликнуться Data Scientist Опыт 1-3 года Можно удалённо ООО Ок Софт Москва Деловой центр и еще 3 Откликнуться Компании для вас Ventra 801 активная вакансия Посмотреть Банк ПСБ 873 активные вакансии Посмотреть Просвещение 51 активная вакансия Посмотреть Группа компаний НВМ 136 активных вакансий Посмотреть «Zunami» 4 активные вакансии Посмотреть Drivee 13 активных вакансий Посмотреть SkillStaff 49 активных вакансий Посмотреть Selecty 76 активных вакансий Посмотреть ДИКСИ, группа компаний 3737 активных вакансий Посмотреть ForteBank 110 активных вакансий Посмотреть МТС 1899 активных вакансий Посмотреть IBS 103 активные вакансии Посмотреть АФЛТ-Системс 31 активная вакансия Посмотреть Северсталь 488 активных вакансий Посмотреть билайн 1474 активные вакансии Посмотреть Бристоль, сеть магазинов 3057 активных вакансий Посмотреть Т1 147 активных вакансий Посмотреть IT Холдинг Kazdream 18 активных вакансий Посмотреть Сбер Банк 55 активных вакансий Посмотреть СБЕР 3472 активные вакансии Посмотреть БКС Банк 17 активных вакансий Посмотреть Островок 47 активных вакансий Посмотреть По\xa0вашему запросу ещё будут появляться новые вакансии. Присылать\xa0вам? Data Scientist Ключевые слова в названии вакансии, в названии компании и\xa0в описании вакансии Даю согласие на\xa0обработку персональных данных на\xa0получение ссылки на\xa0автоматически подобранные вакансии в\xa0соответствии с Условиями обработки . Ознакомлен с Правами, связанными с\xa0обработкой, механизмом их\xa0реализации и\xa0последствиями согласия и\xa0отказа . В\xa0мессенджер На\xa0почту Стажер Data scientist Без опыта ПАО Банк ПСБ, Старт карьеры Москва Новокузнецкая Откликнуться Системный аналитик Опыт 3-6 лет АО Просвещение Москва Достоевская и еще 1 Откликнуться Аналитик данных (Data Scientist) Опыт 1-3 года Можно удалённо Группа компаний НВМ Краснодар, р-н Прикубанский Откликнуться Data Scientist - стажер Без опыта «Zunami» Калининград, р-н Ленинградский Откликнуться ИИ специалист от 70\u202f000 ₽ за\xa0месяц, на руки Опыт 1-3 года Выплаты: Два раза в\xa0месяц Дверянин Набережные Челны, БАЗА ЗАО ,,ПОДРЯД,,, 1 Можно без резюме Откликнуться Junior Data Scientist (Pricing) Без опыта Drivee Якутск Откликнуться Python/DS специалист (Middle) Опыт 3-6 лет Можно удалённо SkillStaff Москва Откликнуться Ведущий разработчик искусственного интеллекта/Middle Data scientist 180\u202f000 ₽ за\xa0месяц, на руки Опыт 1-3 года Можно удалённо Выплаты: Два раза в\xa0месяц Геномед Москва Сокольники Откликнуться Системный аналитик Опыт 3-6 лет ООО Современные Фонды Недвижимости Москва Откликнуться AI Engineer Опыт 1-3 года HALYK FINANCE, дочерняя организация АО Народный банк Алматы Алатау Откликнуться Data Scientist до 300\u202f000 ₽ за\xa0месяц, на руки Опыт 3-6 лет Можно удалённо Выплаты: Два раза в\xa0месяц Selecty Москва Библиотека им.Ленина и еще 3 Откликнуться Middle Analyst Опыт 1-3 года Можно удалённо Adviva Москва Откликнуться Data Scientist Опыт 3-6 лет Можно удалённо Tech Duck Польша Откликнуться Data Scientist (Поддержка и развитие моделей прогнозирования спроса) Опыт 1-3 года Можно удалённо ДИКСИ. IT Москва Откликнуться Junior/Middle Python Data Scientist Опыт 1-3 года Можно удалённо SL Soft Москва Откликнуться Менеджер проектов от 90\u202f000 ₽ за\xa0месяц, на руки Опыт 1-3 года Выплаты: Два раза в\xa0месяц Paper Planes Москва Белорусская и еще 3 Откликнуться Strong Junior / Middle Risk Quant Опыт 1-3 года АО ForteBank Астана, улица Достык, 8/1 Откликнуться Стажер-ресечер 60\u202f000 ₽ за\xa0месяц, до вычета налогов Без опыта Выплаты: Два раза в\xa0месяц «МТС», Стажировки Москва Марксистская и еще 2 Откликнуться 1 2 3 ... Быстрые фильтры подбора вакансий Без опыта работы Вечерняя и ночная Вахтовый метод График 5/2 Гибкий график Два через два За\xa0последние три дня За\xa0сутки От\xa0прямых работодателей Полный день По совместительству Подработка Полная занятость Для людей с\xa0инвалидностью Сменный график Сутки через двое Сутки через трое Три через три Удаленная работа Частичная занятость rabota.by Поиск сотрудников Помощь Наши вакансии Реклама на сайте Требования к ПО Политика обработки cookie Настройки cookie Напишите нам Каталог компаний Поиск по\xa0вакансиям в Минске Работа рядом с\xa0метро Соискателям Все сервисы Кадровые агентства Беларуси Производственный календарь Боты для уведомлений Мобильное приложение Этика и\xa0комплаенс Оказание услуг Использование сайтов Политика обработки данных Пользовательское соглашение ООО «ВСЯ РАБОТА» Зарегистрировано Минским горисполкомом 09.07.2020. 220004, г. Минск, ул. К. Цеткин, 24-76. Режим работы предприятия: пн.-пт.\xa009.00-18.00, вых.\xa0дн. –\xa0сб., вс. Режим работы сайта\xa0– круглосуточно.\xa0E-mail ООО «ВСЯ РАБОТА» support@hh.by р/с BY51ALFA30122667720010270000\xa0ЗАО "Альфа-банк" 220013\xa0г. Минск, ул. Сурганова, 43‑47 Русский © 2026 ООО «ВСЯ РАБОТА» УНП 193441893'

In [150]:
print("Data Scientist" in page_text)

True

In [151]:
qa_tags = soup.find_all(
    attrs={"data-qa": True}
)
qa_tags

[<div data-qa="lux-container"><div class="print-logo-wrapper"><svg class="print-logo" fill="none" height="40" viewbox="0 0 136 22" width="136" xmlns="http://www.w3.org/2000/svg"><path d="M19.14 22H2.86A2.86 2.86 0 0 1 0 19.14V2.86A2.86 2.86 0 0 1 2.86 0h16.28A2.86 2.86 0 0 1 22 2.86v16.28A2.86 2.86 0 0 1 19.14 22" fill="#E80200"></path><path d="M17.38 9.515a4.564 4.564 0 0 0-4.565-4.565H5.28v12.1h3.08v-2.97h3.693l2.027 2.97h3.3l-2.404-3.512a4.58 4.58 0 0 0 2.404-4.023M12.815 11H8.36V8.03h4.455c.817 0 1.485.668 1.485 1.485S13.632 11 12.815 11" fill="#fff"></path><path d="M106.15 13.53c-1.029 0-1.87.84-1.87 1.87s.841 1.87 1.87 1.87 1.87-.84 1.87-1.87-.841-1.87-1.87-1.87M86.02 1.43h-3.3v3.52h-2.31v3.08h2.31v6.82c0 1.218.982 2.2 2.2 2.2h3.63v-3.08h-2.53V8.03h2.53V4.95h-2.53zm45.752 3.52-2.844 7.52-2.868-7.52h-3.528l4.604 12.1h.063l-1.249 3.3h3.52l5.83-15.4zM47.52 6.05c-1.053-.801-2.286-1.273-3.52-1.312-3.567-.126-6.482 2.718-6.49 6.27.165 4.046 3.276 6.38 6.49 6.27a6.34 6.34 0 0 0 2.97-.872v.652h3.3V4.966h-2.2zm-.55 6.576A3.17 3.17 0 0 1 44 14.198a3.204 3.204 0 0 1-2.97-3.19A3.21 3.21 0 0 1 44 7.818c1.862-.118 3.394 1.32 3.41 3.19a3.3 3.3 0 0 1-.44 1.618m52.8-6.576c-1.053-.801-2.286-1.273-3.52-1.312-3.567-.126-6.482 2.718-6.49 6.27.165 4.046 3.276 6.38 6.49 6.27a6.34 6.34 0 0 0 2.97-.872v.652h3.3V4.966h-2.2zm-.55 6.576a3.17 3.17 0 0 1-2.97 1.572 3.204 3.204 0 0 1-2.97-3.19 3.21 3.21 0 0 1 2.97-3.19c1.862-.118 3.394 1.32 3.41 3.19a3.3 3.3 0 0 1-.44 1.618M73.04 4.51A6.487 6.487 0 0 0 66.55 11c0 3.575 2.9 6.49 6.49 6.49 3.575 0 6.49-2.9 6.49-6.49 0-3.575-2.9-6.49-6.49-6.49m0 9.68A3.187 3.187 0 0 1 69.85 11c0-1.76 1.422-3.19 3.19-3.19A3.187 3.187 0 0 1 76.23 11a3.187 3.187 0 0 1-3.19 3.19m43.01-9.452c-1.021.04-2.051.37-2.97.943V1.438h-3.3V17.05h3.3v-.652a6.34 6.34 0 0 0 2.97.872c3.214.11 6.325-2.216 6.49-6.27a6.257 6.257 0 0 0-6.49-6.262m0 9.46a3.15 3.15 0 0 1-2.97-1.572 3.3 3.3 0 0 1-.44-1.618c.016-1.87 1.548-3.308 3.41-3.19a3.21 3.21 0 0 1 2.97 3.19 3.205 3.205 0 0 1-2.97 3.19m-57.53-9.46c-1.021.04-2.05.37-2.97.943V1.438h-3.3V17.05h3.3v-.652a6.34 6.34 0 0 0 2.97.872c3.214.11 6.325-2.216 6.49-6.27a6.257 6.257 0 0 0-6.49-6.262m0 9.46a3.15 3.15 0 0 1-2.97-1.572 3.3 3.3 0 0 1-.44-1.618c.016-1.87 1.548-3.308 3.41-3.19a3.21 3.21 0 0 1 2.97 3.19 3.204 3.204 0 0 1-2.97 3.19M31.57 6.404V4.95h-3.3v12.1h3.3v-4.4c.047-2.137 1.131-3.504 2.82-4.101a5.2 5.2 0 0 1 1.8-.299h.33v-3.3h-.33c-1.713.024-3.34.55-4.62 1.454" fill="#000"></path></svg></div><span><!--noindex--></span><noscript><div class="important-notifications--Wdz4FI5LObEPxJRr"><div class="bloko-columns-wrapper"><div class="bloko-v-spacing bloko-v-spacing_base-3"></div><div class="bloko-column bloko-column_xs-4 bloko-column_s-8 bloko-column_m-12 bloko-column_l-16"><div class="site-exceptions-content--pmV5YviJbpc0mLZW"><div class="bloko-text">Для работы с нашим сайтом необходимо, чтобы Вы включили JavaScript в вашем браузере.</div></div></div><div class="bloko-v-spacing bloko-v-spacing_base-3"></div></div></div></noscript><span><!--/noindex--></span><div class="supernova-navi-container supernova-navi-container_sticky"><header class="supernova-navi-wrapper supernova-navi-wrapper_theme-desktop-light supernova-navi-wrapper_theme-s-shaded supernova-navi-wrapper_theme-xs-shaded"><div class="supernova-navi-inner-wrapper"><div class="supernova-navi HH-Supernova-NotificationManager-Container supernova-navi_shaded supernova-navi_anonymous" data-qa=""><a aria-label="Главная страница сайта" class="supernova-logo-wrapper supernova-logo-wrapper-xs-tiny" href="/"><span class="supernova-logo supernova-logo_inversed supernova-logo_jobs-tut-by" data-qa="supernova-logo" tabindex="-1"></span></a><div class="supernova-navi-item supernova-navi-item_user-type-switcher hidden--zQvzRI4s9Yss_6gY xs--quJiiB_mowyBUoRZ s--KvamembDHasuW_K8"><div class="supernova-dropdown-anchor supernova-dropdown-anchor_full-height"><div><button class="magritte-link___b4rEM_7-1-39 magritte-link_mode_primary___l6una_7-1-39 magritte-link_style_constant___w9ENv_7-1-39 magritte-link_block___Lk0iO_7-1-39" data-qa="mainmenu_userTypeSwitcher" type="button"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-3-regular___Nhtlp_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="mainmenu_userTypeSwitcher-text">Ищу работу</span><span class="magritte-link__icon-right___VVZpb_7-1-39 magritte-icon-without-color___P5ivQ_7-1-39"><span class="magritte-vertically-centered-icon___Zstk8_7-1-39"><svg aria-hidden="true" class="magritte-icon___rRr4Q_15-0-0 magritte-icon_initial-primary___KhLAU_15-0-0" data-qa="mainmenu_userTypeSwitcher-icon-external" fill="none" focusable="false" height="24" role="img" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g><path clip-rule="evenodd" d="m12 17.273-8-8L5.273 8 12 14.727 18.727 8 20 9.273z" fill="currentColor" fill-rule="evenodd"></path></g></svg></span></span></span></span></button></div></div></div><div class="supernova-navi-item supernova-navi-item_user-type-segmented hidden--zQvzRI4s9Yss_6gY m--dwUAzHYYW8ILoCTa l--dofkdKozM9oEslcK"><div class="container--dtP4rvxajZ8RLG8O" data-qa="userTypeSegmented"><div class="magritte-container___V6-Lq_2-1-36 magritte-stretched___B1oB6_2-1-36"><div class="magritte-segments-container___0TT81_2-1-36 magritte-small-container___kSY-C_2-1-36 magritte-stretched-container___z0WU6_2-1-36"><label class="magritte-segment-wrapper___5l67i_2-1-36"><input checked="" class="magritte-input___Vul7O_2-1-36" data-qa="userTypeSegmentedApplicant" type="radio" value="userTypeSegmentedApplicant"/><span aria-hidden="false" class="magritte-label___xwTC5_2-1-36 magritte-segment___fiYEo_2-1-36"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-3-regular___Nhtlp_5-3-11 magritte-text-ellipsis___-DV8z_5-3-11">Ищу работу</span></span><span aria-hidden="true" class="magritte-label___xwTC5_2-1-36 magritte-segment___fiYEo_2-1-36 magritte-selected___HzokM_2-1-36" style="display:flex"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-subtitle-2-semibold___3q3c-_5-3-11 magritte-text-ellipsis___-DV8z_5-3-11">Ищу работу</span></span></label><label class="magritte-segment-wrapper___5l67i_2-1-36"><input class="magritte-input___Vul7O_2-1-36" data-qa="userTypeSegmentedEmployer" type="radio" value="userTypeSegmentedEmployer"/><span aria-hidden="false" class="magritte-label___xwTC5_2-1-36 magritte-segment___fiYEo_2-1-36"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-3-regular___Nhtlp_5-3-11 magritte-text-ellipsis___-DV8z_5-3-11">Ищу сотрудника</span></span></label></div><div aria-hidden="true" class="magritte-slide-container___Es5AN_2-1-36 magritte-small-container___kSY-C_2-1-36"><div class="magritte-segment___fiYEo_2-1-36 magritte-selected___HzokM_2-1-36 magritte-slide___mUofG_2-1-36" style="display:none;width:0px;transform:none"><div class="magritte-segments-container___0TT81_2-1-36 magritte-small-container___kSY-C_2-1-36 magritte-container-clone___i9oSw_2-1-36 magritte-stretched-container___z0WU6_2-1-36" style="transform:none"><div class="magritte-segment-wrapper___5l67i_2-1-36" style="width:0px"><span aria-hidden="true" class="magritte-label___xwTC5_2-1-36 magritte-segment___fiYEo_2-1-36 magritte-selected___HzokM_2-1-36"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-subtitle-2-semibold___3q3c-_5-3-11 magritte-text-ellipsis___-DV8z_5-3-11">Ищу работу</span></span></div><div class="magritte-segment-wrapper___5l67i_2-1-36" style="width:0px"><span aria-hidden="true" class="magritte-label___xwTC5_2-1-36 magritte-segment___fiYEo_2-1-36 magritte-selected___HzokM_2-1-36"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-subtitle-2-semibold___3q3c-_5-3-11 magritte-text-ellipsis___-DV8z_5-3-11">Ищу сотрудника</span></span></div></div></div></div></div></div></div><div class="supernova-navi-item hidden--zQvzRI4s9Yss_6gY l--dofkdKozM9oEslcK"><div><a class="container--j4NR0XcPvN4DXL8p" data-qa="allServices-button" href="/services" tabindex="0"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-2-regular___ia7GB_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="allServices-button-text"><span class="link-content--MgBqUITW28vx87Rd"><span class="content-container--UQRnf82zslBLDaIN"><span class="text-container--CTBdD_w5GI82jAGE text-container-shaded--YxkrjdQJu1AkKzFY" data-qa="mainmenu_allServices"><span class="text--ELyQqnU54MsxbxIx"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-2-regular___ia7GB_5-3-11">Сервисы</span></span></span></span></span></span></span></span></a></div></div><div class="supernova-navi-item hidden--zQvzRI4s9Yss_6gY l--dofkdKozM9oEslcK"><div><a class="magritte-link___b4rEM_7-1-39 magritte-link_mode_primary___l6una_7-1-39 magritte-link_style_constant___w9ENv_7-1-39 magritte-link_block___Lk0iO_7-1-39" data-qa="supernova-help-feedback-link" href="/feedback" tabindex="0"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-3-regular___Nhtlp_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="supernova-help-feedback-link-text">Помощь</span></span></span></a></div></div><div class="supernova-navi-item hidden--zQvzRI4s9Yss_6gY m--dwUAzHYYW8ILoCTa"><div><button class="container--j4NR0XcPvN4DXL8p" data-qa="moreItems-button" type="button"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-2-regular___ia7GB_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="moreItems-button-text"><span class="link-content--MgBqUITW28vx87Rd"><span class="content-container--UQRnf82zslBLDaIN"><span class="text-container--CTBdD_w5GI82jAGE text-container-shaded--YxkrjdQJu1AkKzFY" data-qa="mainmenu_moreItems"><span class="text--ELyQqnU54MsxbxIx"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-2-regular___ia7GB_5-3-11">Ещё</span></span><svg aria-hidden="true" class="magritte-icon___rRr4Q_15-0-0 magritte-icon_initial-primary___KhLAU_15-0-0" fill="none" focusable="false" height="16" role="img" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><g><path clip-rule="evenodd" d="m8 11.5 5-5-.99-.99L8 9.52 3.99 5.51 3 6.5z" fill="currentColor" fill-rule="evenodd"></path></g></svg></span></span></span></span></span></span></button></div></div><div class="supernova-navi-fill"></div><div class="supernova-navi-item supernova-navi-item_search supernova-navi-item_active"><form action="/search/vacancy" method="GET"><div><button class="container--j4NR0XcPvN4DXL8p" data-qa="searchVacancy-button" role="link" type="button"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-2-regular___ia7GB_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="searchVacancy-button-text"><span class="link-content--MgBqUITW28vx87Rd"><span class="content-container--UQRnf82zslBLDaIN"><span class="text-container--CTBdD_w5GI82jAGE hide-text-on-mobile--AibhEmDnClcujltv text-container-shaded--YxkrjdQJu1AkKzFY text-container-active--iU2ZjIWkLgIIv5B9" data-qa="supernova-search"><svg aria-hidden="true" class="magritte-icon___rRr4Q_15-0-0 magritte-icon_initial-primary___KhLAU_15-0-0" fill="none" focusable="false" height="16" role="img" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><g><g><path clip-rule="evenodd" d="M.496 7.247c0-3.375 1.688-6.75 6.75-6.75s6.75 3.375 6.75 6.75c0 1.6-.379 3.2-1.318 4.441L15.5 14.51l-.99.99-2.816-2.816c-1.045.81-2.495 1.313-4.448 1.313-5.062 0-6.75-3.375-6.75-6.75m1.4 0c0-1.48.373-2.81 1.153-3.745.742-.89 2.003-1.605 4.197-1.605s3.456.715 4.198 1.605c.78.936 1.152 2.265 1.152 3.745s-.372 2.809-1.152 3.744c-.742.89-2.003 1.606-4.198 1.606-2.194 0-3.455-.716-4.197-1.606-.78-.935-1.153-2.265-1.153-3.744" fill="currentColor" fill-rule="evenodd"></path></g></g></svg><span class="text--ELyQqnU54MsxbxIx"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-subtitle-1-semibold___6uZ9I_5-3-11">Поиск</span></span></span></span></span></span></span></span></button></div><input name="from" type="hidden" value="header-menu"/><input name="hhtmFromLabel" type="hidden" value="header"/><input name="hhtmFrom" type="hidden" value="vacancy_search_list"/></form></div><div class="supernova-navi-item supernova-navi-item_geo-switcher hidden--zQvzRI4s9Yss_6gY m--dwUAzHYYW8ILoCTa l--dofkdKozM9oEslcK"><div><button aria-expanded="false" aria-haspopup="dialog" aria-label="Выбор региона,Минск" class="container--j4NR0XcPvN4DXL8p" data-qa="geoSwitcher-button" type="button"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-2-regular___ia7GB_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="geoSwitcher-button-text"><span class="link-content--MgBqUITW28vx87Rd"><span class="content-container--UQRnf82zslBLDaIN"><span class="text-container--CTBdD_w5GI82jAGE text-container-shaded--YxkrjdQJu1AkKzFY" data-qa="geo-switcher"><svg aria-hidden="true" class="magritte-icon___rRr4Q_15-0-0 magritte-icon_initial-primary___KhLAU_15-0-0" fill="none" focusable="false" height="16" role="img" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><g><g><path clip-rule="evenodd" d="M3.548 4.543 8.666 2.35C12.361.767 14.208-.025 15.116.884c.909.908.117 2.755-1.466 6.45l-2.193 5.118c-.884 2.06-1.325 3.09-1.995 3.047-.67-.045-.973-1.124-1.577-3.283l-.897-3.204-3.204-.897C1.625 7.511.546 7.21.501 6.538s.987-1.111 3.047-1.995m5.685 7.295-1.11-3.961-3.961-1.11c-.536-.15-.975-.273-1.335-.382.343-.155.761-.336 1.273-.555l5.117-2.193c1.89-.81 3.167-1.353 4.087-1.604.444-.12.681-.138.796-.133.005.115-.012.352-.133.796-.25.92-.794 2.196-1.604 4.087L10.17 11.9c-.22.512-.4.93-.555 1.273-.109-.36-.232-.799-.382-1.335m4.96-9.922s-.01 0-.022-.008a.1.1 0 0 1 .022.008m-.101-.087q-.01-.02-.008-.021.001-.002.008.021" fill="currentColor" fill-rule="evenodd"></path></g></g></svg><span class="text--ELyQqnU54MsxbxIx"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-2-regular___ia7GB_5-3-11"><span class="geo-switcher-text--kroZ85utIA8Kzm0C">Минск</span></span></span></span></span></span></span></span></span></button></div></div><div class="supernova-navi-item supernova-login-wrapper supernova-navi-item_button hidden--zQvzRI4s9Yss_6gY m--dwUAzHYYW8ILoCTa l--dofkdKozM9oEslcK"><a class="magritte-button___Pubhr_7-2-24 magritte-button_mode-secondary___xYz4-_7-2-24 magritte-button_size-small___ZAmsS_7-2-24 magritte-button_style-neutral___I5qS5_7-2-24" data-qa="login" href="/account/login?role=applicant&amp;backurl=%2Fsearch%2Fvacancy%3Ftext%3DData%2BScientist&amp;hhtmFrom=vacancy_search_list" role="button" tabindex="0"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_full-width___vgWH5_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-button-view___53Slm_7-2-24"><span class="magritte-button__content___BXYU0_7-2-24"><span class="magritte-button__label___zplmt_7-2-24">Войти</span></span></span></span></a></div><div class="supernova-navi-item supernova-login-wrapper hidden--zQvzRI4s9Yss_6gY xs--quJiiB_mowyBUoRZ s--KvamembDHasuW_K8"><div><a class="magritte-link___b4rEM_7-1-39 magritte-link_mode_primary___l6una_7-1-39 magritte-link_style_constant___w9ENv_7-1-39 magritte-link_block___Lk0iO_7-1-39" data-qa="mainmenu_profile-link" href="/account/login?role=applicant&amp;backurl=%2Fsearch%2Fvacancy%3Ftext%3DData%2BScientist" tabindex="0"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-subtitle-2-semibold___3q3c-_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="mainmenu_profile-link-text">Войти</span></span></span></a></div></div><div class="supernova-navi-item supernova-signup-wrapper supernova-navi-item_button hidden--zQvzRI4s9Yss_6gY m--dwUAzHYYW8ILoCTa l--dofkdKozM9oEslcK"><a class="magritte-button___Pubhr_7-2-24 magritte-button_mode-primary___wU8PN_7-2-24 magritte-button_size-small___ZAmsS_7-2-24 magritte-button_style-neutral___I5qS5_7-2-24" data-qa="signup" href="/account/signup?backurl=%2Fapplicant%2Fresumes%2Fnew&amp;hhtmFrom=vacancy_search_list&amp;hhtmFromLabel=header" role="button" tabindex="0"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_full-width___vgWH5_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-button-view___53Slm_7-2-24"><span class="magritte-button__content___BXYU0_7-2-24"><span class="magritte-button__label___zplmt_7-2-24">Создать резюме</span></span></span></span></a></div><div class="supernova-navi-item hidden--zQvzRI4s9Yss_6gY xs--quJiiB_mowyBUoRZ s--KvamembDHasuW_K8"><button aria-label="navi-button-mobile" class="magritte-button___Pubhr_7-2-24 magritte-button_mode-tertiary___ZMpad_7-2-24 magritte-button_size-small___ZAmsS_7-2-24 magritte-button_textless___XBvNJ_7-2-24 magritte-button_style-constant___vP0wU_7-2-24 magritte-button_with-icon___znqnP_7-2-24" type="button"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_full-width___vgWH5_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-button-view___53Slm_7-2-24"><span class="magritte-button__content___BXYU0_7-2-24"><span class="magritte-button__icon___912gw_7-2-24"><svg aria-hidden="true" class="magritte-icon___rRr4Q_15-0-0 magritte-icon_initial-primary___KhLAU_15-0-0" fill="none" focusable="false" height="24" role="img" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g><path d="M20 6.8H4V5h16z" fill="currentColor"></path><path d="M20 12.9H4v-1.8h16z" fill="currentColor"></path><path d="M4 19h16v-1.8H4z" fill="currentColor"></path></g></svg></span></span></span></span></button></div></div></div></header></div><div class="HH-MainContent HH-Supernova-MainContent"><main class="main-content main-content_broad-spacing"><div class="magritte-grid-layout___JiVGG_3-0-13"><div class="magritte-grid-layout-content___fzkS0_3-0-13" data-qa="main-content"><div class="magritte-grid-column___rhP24_3-0-13 magritte-grid-column_xs-4___eVCYh_3-0-13 magritte-grid-column_s-8___vihhu_3-0-13 magritte-grid-column_m-12___KQXbY_3-0-13 magritte-grid-column_l-12___vHTF5_3-0-13

In [152]:
print(len(qa_tags))

564

In [153]:
for tag in qa_tags[:100]:
    print(
        tag.name,
        tag.get("data-qa"),
        tag.get_text(" ", strip=True)[:100]
    )

div lux-container Для работы с нашим сайтом необходимо, чтобы Вы включили JavaScript в вашем браузере. Ищу работу Ищу
div  Ищу работу Ищу работу Ищу работу Ищу сотрудника Ищу работу Ищу сотрудника Сервисы Помощь Ещё Поиск М
span supernova-logo
button mainmenu_userTypeSwitcher Ищу работу
span mainmenu_userTypeSwitcher-text Ищу работу
svg mainmenu_userTypeSwitcher-icon-external
div userTypeSegmented Ищу работу Ищу работу Ищу сотрудника Ищу работу Ищу сотрудника
input userTypeSegmentedApplicant
input userTypeSegmentedEmployer
a allServices-button Сервисы
span allServices-button-text Сервисы
span mainmenu_allServices Сервисы
a supernova-help-feedback-link Помощь
span supernova-help-feedback-link-text Помощь
button moreItems-button Ещё
span moreItems-button-text Ещё
span mainmenu_moreItems Ещё
button searchVacancy-button Поиск
span searchVacancy-button-text Поиск
span supernova-search Поиск
button geoSwitcher-button Минск
span geoSwitcher-button-text Минск
span geo-switcher Минск
a login Войти
a mainmenu_profile-link Войти
span mainmenu_profile-link-text Войти
a signup Создать резюме
div main-content Data Scientist
input search-input
button input-clearable-button
svg input-clearable-button-svg
input vacancy-serp__compensation
button vacancy-saved-search-create
div main-content Регион График Рабочие часы Опыт Тип занятости Уровень дохода Ещё фильтры
label chip
input header-search-filters-chip
svg chip-addon
div chip Регион
button search-filter-area-chip Регион
svg chip-addon
div chip График
button search-filter-work_schedule_by_days-chip График
svg chip-addon
div chip Рабочие часы
button search-filter-working_hours-chip Рабочие часы
svg chip-addon
div chip Опыт
button search-filter-experience-chip Опыт
svg chip-addon
div chip Тип занятости
button search-filter-employment_form-chip Тип занятости
svg chip-addon
div chip Уровень дохода
button search-filter-compensation_per_mode-chip Уровень дохода
svg chip-addon
label chip Ещё фильтры
input header-search-more-filters
div main-content Найдено 264 вакансии «Data Scientist» Data Scientist Опыт 1-3 года Ventra Москва Откликнуться Data S
div vacancies-search-header Найдено 264 вакансии «Data Scientist»
div title-container Найдено 264 вакансии «Data Scientist»
h1 title Найдено 264 вакансии «Data Scientist»
input short_description
input full_description
section vacancy-serp__results Data Scientist Опыт 1-3 года Ventra Москва Откликнуться Data Scientist Опыт 1-3 года Можно удалённо
article vacancy-serp__vacancy Data Scientist Опыт 1-3 года Ventra Москва Откликнуться
a serp-item__title Data Scientist
span serp-item__title-text Data Scientist
data vacancy-serp__vacancy-work-experience-between1And3 Опыт 1-3 года
a trusted-employer-link
a vacancy-serp__vacancy_employer-hh-rating
span vacancy-serp-item-activity
a vacancy-serp__vacancy-employer-logo
img vacancy-serp__vacancy-employer-logo-image-small
a vacancy-serp__vacancy-employer Ventra
span vacancy-serp__vacancy-employer-text Ventra
span vacancy-serp__vacancy-address Москва
a vacancy-serp__vacancy_response Откликнуться
article vacancy-serp__vacancy Data Scientist Опыт 1-3 года Можно удалённо ООО Ок Софт Москва Деловой центр и еще 3 Откликнуться
a serp-item__title Data Scientist
span serp-item__title-text Data Scientist
data vacancy-serp__vacancy-work-experience-between1And3 Опыт 1-3 года
span vacancy-label-work-schedule-remote Можно удалённо
a trusted-employer-link
a vacancy-serp__vacancy-employer ООО Ок Софт
span vacancy-serp__vacancy-employer-text ООО Ок Софт
span vacancy-serp__vacancy-address Москва
span address-metro-station-name Деловой центр
span address-metro-station-name
span address-metro-station-name
span address-metro-station-name
a vacancy-serp__vacancy_response Откликнуться
div branded-employers-wizard-header Компании для вас
div scrollable-container__wrapper Ventra 801 активная вакансия Посмотреть Банк ПСБ 873 активные вакансии Посмотреть Просвещение 51 акт
button scrollable-container__scroll-button-left
svg scrollable-container__scroll-button-left-svg
div scrollable-container__fade Ventra 801 активная вакансия Посмотреть Банк ПСБ 873 активные вакансии Посмотреть Просвещение 51 акт
div scrollable-container__overflow-container Ventra 801 активная вакансия Посмотреть Банк ПСБ 873 активные вакансии Посмотреть Просвещение 51 акт
div scrollable-container__position-container Ventra 801 активная вакансия Посмотреть Банк ПСБ 873 активные вакансии Посмотреть Просвещение 51 акт
div branded-employers-wizard-gallery-card Ventra 801 активная вакансия Посмотреть
div branded-employers-wizard-gallery-card-logo

In [154]:
cards = soup.find_all(
    "article",
    attrs={"data-qa": "vacancy-serp__vacancy"}
)
print(len(cards))

20

In [155]:
print(cards[0].prettify()[:5000])

<article aria-disabled="false" class="magritte-card___bhGKz_8-6-4 magritte-card-style-primary___eZ6aX_8-6-4 magritte-card-shadow-level-0___RNbQK_8-6-4 magritte-card-stretched___0Uc0J_8-6-4 magritte-card-press-enabled___kXfCl_8-6-4 magritte-card-hover-enabled___-wolU_8-6-4 magritte-increase-shadow___Lvfmm_8-6-4 magritte-border-default___eT8Lg_8-6-4" data-qa="vacancy-serp__vacancy" style="padding-left:12px;padding-right:12px;padding-top:12px;padding-bottom:12px;--magritte-card-border-radius:24px">
 <div class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_full-width___vgWH5_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0">
  <div class="magritte-flex-container___CVFEY_8-6-4">
   <div class="magritte-text-dynamic___71-Al_5-3-11 magritte-text-dynamic_stretched___wzj-Q_5-3-11">
    <div class="vacancy-card--n77Dj8TY8VIUF0yM font-inter" id="136311467">
     <div class="vacancy-info--ieHKDTkezpEj0Gsx">
      <div class="actions-container-narrow--ERhWyxHyP98YkBk2">
      </div>
      <span class="custom-color-magritte-link--vpnos5EPubw4tVcY vacancy-name-wrapper--PSD41i3dJDUNb5Tr">
       <a class="magritte-link___b4rEM_7-1-39 magritte-link_mode_primary___l6una_7-1-39 magritte-link_style_neutral___iqoW0_7-1-39 magritte-link_enable-visited___Biyib_7-1-39" data-qa="serp-item__title" href="https://hh.ru/vacancy/136311467?query=Data+Scientist" tabindex="0" target="_blank">
        <span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0">
         <span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-title-4-semibold___vUqki_5-3-11">
          <span class="magritte-text___tkzIl_7-1-39" data-qa="serp-item__title-text">
           Data Scientist
          </span>
         </span>
        </span>
       </a>
      </span>
      <div class="magritte-v-spacing___R3QYf_2-1-26" style="--magritte-spacing-xs:8px;--magritte-spacing-s:8px;--magritte-spacing-m:8px;--magritte-spacing-l:8px;--magritte-spacing-xl:8px;--magritte-spacing-xxl:8px">
      </div>
      <div>
       <div class="compensation-labels--vwum2s12fQUurc2J compensation-labels_magritte--pbBIkJ7Ww24ZILKz">
        <div aria-disabled="false" class="magritte-tag___WdGxk_5-3-20 magritte-tag_style-neutral___cw1Bt_5-3-20 magritte-tag_size-medium___Splpy_5-3-20">
         <div class="magritte-tag__label___YHV-o_5-3-20">
          <data data-qa="vacancy-serp__vacancy-work-experience-between1And3" value="1-3">
           Опыт 1-3 года
          </data>
         </div>
        </div>
       </div>
      </div>
      <div class="info-section--YaC_npvTFcwpFd1I">
       <div>
        <div class="magritte-v-spacing___R3QYf_2-1-26" style="--magritte-spacing-xs:24px;--magritte-spacing-s:24px;--magritte-spacing-m:24px;--magritte-spacing-l:24px;--magritte-spacing-xl:24px;--magritte-spacing-xxl:24px">
        </div>
        <div class="company-name-badges-container--ofqQHaTYRFg0JM18">
         <a data-qa="trusted-employer-link" href="/article/19873?hhtmFrom=vacancy_search_list" target="_blank">
          <span class="trusted-employer-check-icon--nJknXR93rX4AV_LR">
           <svg aria-hidden="true" class="magritte-icon___rRr4Q_15-0-0 magritte-icon_initial-accent___E3b-y_15-0-0" fill="none" focusable="false" height="16" role="img" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg">
            <g>
             <g>
              <path clip-rule="evenodd" d="M6.294 14.873c.467.53.989 1.123 1.704 1.123v-.008c.723 0 1.246-.594 1.704-1.124.273-.32.57-.658.828-.762.267-.114.687-.091 1.107-.068l.067.004.027.001c.707.04 1.434.08 1.918-.403.476-.475.435-1.21.395-1.916l-.001-.026-.003-.058c-.024-.416-.048-.845.067-1.114.113-.257.442-.546.764-.826l.018-.016c.525-.461 1.107-.972 1.107-1.686 0-.722-.595-1.244-1.125-1.701-.322-.273-.66-.57-.764-.827-.114-.267-.091-.686-.068-1.105l.004-.067c.048-.714.096-1.453-.394-1.942-.477-.484-1.212-.443-1.92-.403l-.025.001-.059.004c-.416.023-.846.047-1.115-.068-.257-.112-.547-.441-.828-.762l-.016-.018C9.224.58 8.713 0 7.998 0c-.723 0-1.246.594-1.704 1.124-.273.32-.57.658-.828.762-.267.115-.686.091-1.107.068l-.067-.004-.027-.001c-.707-.04-1.434-.08-1.918.403-.476.483-.435 1.209-.395 1.915l.001.027.004.063c.023.422.047.85-.068 1.117-.113.257-.442.546-.764.827l-.017.015C.582 6.778 0 7.288 0 8.002c0 .722.595 1.244 1.125 1.702.322.272.66.57.764.826.114.267.091.686.068 1.105l-.004.067c-.048.714-.096 1.453.394 1.942.477.484 1.212.443 1.92.403l.025-.001.058-.004c.417-.023.847-.047 1.116.068.257.112.547.442.828.763m5.693-8.874-.99-.99-3.999 3.999-2-2-.99.99 2.99 2.99z" fill="currentColor" fill-rule="evenodd">
              </path>
             </g>
            </g>
           </svg>
          </span>
         </a>
         <a data-qa="vacancy-serp__vacancy_employer-hh-rating" href="https://rating.hh.ru/history/rating2025?utm_source=hh.

In [156]:
title_tag = cards[0].find(
    "a",
    attrs={"data-qa": "serp-item__title"}
)
print(title_tag)

<a class="magritte-link___b4rEM_7-1-39 magritte-link_mode_primary___l6una_7-1-39 magritte-link_style_neutral___iqoW0_7-1-39 magritte-link_enable-visited___Biyib_7-1-39" data-qa="serp-item__title" href="https://hh.ru/vacancy/136311467?query=Data+Scientist" tabindex="0" target="_blank"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-title-4-semibold___vUqki_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="serp-item__title-text">Data Scientist</span></span></span></a>

In [157]:
title = title_tag.get_text(
    " ",
    strip=True
)

print(title)

Data Scientist

In [158]:
url = title_tag.get("href")

print(url)

https://hh.ru/vacancy/136311467?query=Data+Scientist

In [159]:
company_tag = cards[0].find(
    attrs={
        "data-qa": "vacancy-serp__vacancy-employer"
    }
)
print(company_tag)

<a class="magritte-link___b4rEM_7-1-39 magritte-link_mode_primary___l6una_7-1-39 magritte-link_style_neutral___iqoW0_7-1-39" data-qa="vacancy-serp__vacancy-employer" href="/employer/1838?hhtmFrom=vacancy_search_list" tabindex="0"><span class="magritte-icon-dynamic___KJ4yJ_15-0-0 magritte-icon-dynamic_hover-enabled___WblhN_15-0-0 magritte-icon-dynamic_press-enabled___aGKHB_15-0-0"><span class="magritte-text___pbpft_5-3-11 magritte-text_style-primary___AQ7MW_5-3-11 magritte-text_typography-label-3-regular___Nhtlp_5-3-11"><span class="magritte-text___tkzIl_7-1-39" data-qa="vacancy-serp__vacancy-employer-text">Ventra</span></span></span></a>

In [160]:
company = company_tag.get_text(
    " ",
    strip=True
)

print(company)

Ventra

In [161]:
address_tag = cards[0].find(
    attrs={
        "data-qa": "vacancy-serp__vacancy-address"
    }
)

In [162]:
address = address_tag.get_text(
    " ",
    strip=True
)

print(address)

Москва

In [163]:

experience_tag = cards[0].select_one(
    '[data-qa^="vacancy-serp__vacancy-work-experience"]'
)
experience = experience_tag.get_text(
    " ",
    strip=True
)

print(experience)

Опыт 1-3 года

In [164]:
card = cards[0]

title_tag = card.find(
    "a",
    attrs={"data-qa": "serp-item__title"}
)

company_tag = card.find(
    attrs={"data-qa": "vacancy-serp__vacancy-employer"}
)

address_tag = card.find(
    attrs={"data-qa": "vacancy-serp__vacancy-address"}
)

experience_tag = card.select_one(
    '[data-qa^="vacancy-serp__vacancy-work-experience"]'
)

In [165]:
title = (
    title_tag.get_text(" ", strip=True)
    if title_tag
    else None
)

url = (
    title_tag.get("href")
    if title_tag
    else None
)

company = (
    company_tag.get_text(" ", strip=True)
    if company_tag
    else None
)

address = (
    address_tag.get_text(" ", strip=True)
    if address_tag
    else None
)

experience = (
    experience_tag.get_text(" ", strip=True)
    if experience_tag
    else None
)

In [166]:
job = {
    "title": title,
    "company": company,
    "address": address,
    "experience": experience,
    "url": url
}

In [167]:
print(job)

{'title': 'Data Scientist', 'company': 'Ventra', 'address': 'Москва', 'experience': 'Опыт 1-3 года', 'url': 'https://hh.ru/vacancy/136311467?query=Data+Scientist'}

In [168]:
card = cards[3]

for tag in card.find_all(attrs={"data-qa": True}):
    print(
        tag.name,
        tag.get("data-qa"),
        tag.get_text(" ", strip=True)
    )

a serp-item__title Системный аналитик
span serp-item__title-text Системный аналитик
data vacancy-serp__vacancy-work-experience-between3And6 Опыт 3-6 лет
a trusted-employer-link
a vacancy-serp__vacancy_employer-hh-rating
span vacancy-serp-item-activity
a vacancy-serp__vacancy-employer-logo
img vacancy-serp__vacancy-employer-logo-image-small
a vacancy-serp__vacancy-employer АО Просвещение
span vacancy-serp__vacancy-employer-text АО Просвещение
span vacancy-serp__vacancy-address Москва
span address-metro-station-name Достоевская
span address-metro-station-name
a vacancy-serp__vacancy_response Откликнуться

In [169]:
query = "Data Scientist"

jobs = []

for card in cards:

    title_tag = card.find(
        "a",
        attrs={"data-qa": "serp-item__title"}
    )

    company_tag = card.find(
        attrs={"data-qa": "vacancy-serp__vacancy-employer"}
    )

    address_tag = card.find(
        attrs={"data-qa": "vacancy-serp__vacancy-address"}
    )

    experience_tag = card.select_one(
        '[data-qa^="vacancy-serp__vacancy-work-experience"]'
    )

    title = (
        title_tag.get_text(" ", strip=True)
        if title_tag
        else None
    )

    company = (
        company_tag.get_text(" ", strip=True)
        if company_tag
        else None
    )

    address = (
        address_tag.get_text(" ", strip=True)
        if address_tag
        else None
    )

    experience = (
        experience_tag.get_text(" ", strip=True)
        if experience_tag
        else None
    )

    url = (
        title_tag.get("href")
        if title_tag
        else None
    )

    job = {
        "title": title,
        "company": company,
        "address": address,
        "experience": experience,
        "url": url,
        "query": query
    }

    jobs.append(job)

In [170]:
print(len(jobs))
print(jobs[:5])

20
[{'title': 'Data Scientist', 'company': 'Ventra', 'address': 'Москва', 'experience': 'Опыт 1-3 года', 'url': 'https://hh.ru/vacancy/136311467?query=Data+Scientist', 'query': 'Data Scientist'}, {'title': 'Data Scientist', 'company': 'ООО Ок Софт', 'address': 'Москва', 'experience': 'Опыт 1-3 года', 'url': 'https://hh.ru/vacancy/136327913?query=Data+Scientist', 'query': 'Data Scientist'}, {'title': 'Стажер Data scientist', 'company': 'ПАО Банк ПСБ, Старт карьеры', 'address': 'Москва', 'experience': 'Без опыта', 'url': 'https://hh.ru/vacancy/136021202?query=Data+Scientist', 'query': 'Data Scientist'}, {'title': 'Системный аналитик', 'company': 'АО Просвещение', 'address': 'Москва', 'experience': 'Опыт 3-6 лет', 'url': 'https://hh.ru/vacancy/136292099?query=Data+Scientist', 'query': 'Data Scientist'}, {'title': 'Аналитик данных (Data Scientist)', 'company': 'Группа компаний НВМ', 'address': 'Краснодар, р-н Прикубанский', 'experience': 'Опыт 1-3 года', 'url': 'https://hh.ru/vacancy/136265966?query=Data+Scientist', 'query': 'Data Scientist'}]

In [171]:
for job in jobs[:5]:
    print("Запрос:", job["query"])
    print("Вакансия:", job["title"])
    print("Компания:", job["company"])
    print("Опыт:", job["experience"])
    print("Город:", job["address"])
    print("URL:", job["url"])
    print("-" * 50)

Запрос: Data Scientist
Вакансия: Data Scientist
Компания: Ventra
Опыт: Опыт 1-3 года
Город: Москва
URL: https://hh.ru/vacancy/136311467?query=Data+Scientist
--------------------------------------------------
Запрос: Data Scientist
Вакансия: Data Scientist
Компания: ООО Ок Софт
Опыт: Опыт 1-3 года
Город: Москва
URL: https://hh.ru/vacancy/136327913?query=Data+Scientist
--------------------------------------------------
Запрос: Data Scientist
Вакансия: Стажер Data scientist
Компания: ПАО Банк ПСБ, Старт карьеры
Опыт: Без опыта
Город: Москва
URL: https://hh.ru/vacancy/136021202?query=Data+Scientist
--------------------------------------------------
Запрос: Data Scientist
Вакансия: Системный аналитик
Компания: АО Просвещение
Опыт: Опыт 3-6 лет
Город: Москва
URL: https://hh.ru/vacancy/136292099?query=Data+Scientist
--------------------------------------------------
Запрос: Data Scientist
Вакансия: Аналитик данных (Data Scientist)
Компания: Группа компаний НВМ
Опыт: Опыт 1-3 года
Город: Краснодар, р-н Прикубанский
URL: https://hh.ru/vacancy/136265966?query=Data+Scientist
--------------------------------------------------

In [172]:
import pandas as pd
df = pd.DataFrame(jobs)
df.head()

,title,company,address,experience,url,query
0,Data Scientist,Ventra,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136311467?query=Data+Sci...,Data Scientist
1,Data Scientist,ООО Ок Софт,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136327913?query=Data+Sci...,Data Scientist
2,Стажер Data scientist,"ПАО Банк ПСБ, Старт карьеры",Москва,Без опыта,https://hh.ru/vacancy/136021202?query=Data+Sci...,Data Scientist
3,Системный аналитик,АО Просвещение,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/136292099?query=Data+Sci...,Data Scientist
4,Аналитик данных (Data Scientist),Группа компаний НВМ,"Краснодар, р-н Прикубанский",Опыт 1-3 года,https://hh.ru/vacancy/136265966?query=Data+Sci...,Data Scientist

In [173]:
print(df.shape)

(20, 6)

In [174]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       20 non-null     str
 1   company     20 non-null     str
 2   address     20 non-null     str
 3   experience  20 non-null     str
 4   url         20 non-null     str
 5   query       20 non-null     str
dtypes: str(6)
memory usage: 1.1 KB

In [175]:
df.isna().sum()

title         0
company       0
address       0
experience    0
url           0
query         0
dtype: int64

In [176]:
print(df["url"].duplicated().sum())

0

In [177]:
df["title"].value_counts()

title
Data Scientist                                                          4
Системный аналитик                                                      2
Стажер Data scientist                                                   1
Аналитик данных (Data Scientist)                                        1
Data Scientist - стажер                                                 1
ИИ специалист                                                           1
Junior Data Scientist (Pricing)                                         1
Python/DS специалист (Middle)                                           1
Ведущий разработчик искусственного интеллекта/Middle Data scientist     1
AI Engineer                                                             1
Middle Analyst                                                          1
Data Scientist (Поддержка и развитие моделей прогнозирования спроса)    1
Junior/Middle Python Data Scientist                                     1
Менеджер проектов                                                       1
Strong Junior / Middle Risk Quant                                       1
Стажер-ресечер                                                          1
Name: count, dtype: int64

In [178]:
df["experience"].value_counts()

experience
Опыт 1-3 года    11
Опыт 3-6 лет      5
Без опыта         4
Name: count, dtype: int64

In [179]:
df.to_csv(
    "../data/raw/data_scientist_page_1.csv",
    index=False,
    encoding="utf-8-sig"
)

In [180]:
job_url = df.loc[0, "url"]
job_url

'https://hh.ru/vacancy/136311467?query=Data+Scientist'

## Этап 2. Поиск описания вакансии на странице

In [181]:
job_response = requests.get(
    job_url,
    headers=headers,
    timeout=20
)

In [182]:
print(job_response.status_code)
print(job_response.url)
print(job_response.headers.get("Content-Type"))

200
https://hh.ru/vacancy/136311467?query=Data+Scientist
text/html; charset=utf-8

In [183]:
job_soup = BeautifulSoup(
    job_response.text,
    "html.parser"
)

In [184]:
job_qa_tags = job_soup.find_all(
    attrs={"data-qa": True}
)
for tag in job_qa_tags:
    qa = tag.get("data-qa")

    if (
        "description" in qa.lower()
        or "skill" in qa.lower()
        or "salary" in qa.lower()
        or "compensation" in qa.lower()
    ):
        print(
            tag.name,
            qa,
            tag.get_text(" ", strip=True)[:300]
        )

div vacancy-description Требования: От 2 лет коммерческого опыта запуска дата-продуктов в продуктивной среде. Высшее образование и соответствующий опыт в области статистики, математики, информатики или смежных областях. Уверенное знание SQL, Python (pandas, numpy, scikit-learn, LightGBM/XGBoost) алгоритмов машинного обучен
div vacancy-response-question vacancy-response-question_salary_options Какая оплата труда?
a footer_advertisingDescription-xs Реклама на сайте
span footer_advertisingDescription-xs-text Реклама на сайте

In [186]:
skills = [
    "Python",
    "SQL",
    "pandas",
    "numpy",
    "scikit-learn",
    "LightGBM",
    "XGBoost",
    "PyTorch",
    "TensorFlow",
    "Docker",
    "Kubernetes"
]

In [187]:
found_skills = []

In [188]:
description_tag = job_soup.find(
    attrs={"data-qa": "vacancy-description"}
)
description = (
    description_tag.get_text(" ", strip=True)
    if description_tag
    else None
)

In [189]:
for skill in skills:
    if skill.lower() in description.lower():
        found_skills.append(skill)

In [190]:
found_skills.append(skill)

In [191]:
print(found_skills)

['Python', 'SQL', 'pandas', 'numpy', 'scikit-learn', 'LightGBM', 'XGBoost', 'Docker', 'Kubernetes', 'Kubernetes']

In [192]:
skills_count = len(found_skills)

In [193]:
job_data = {
    "title": df.loc[0, "title"],
    "company": df.loc[0, "company"],
    "address": df.loc[0, "address"],
    "experience": df.loc[0, "experience"],
    "url": df.loc[0, "url"],
    "query": df.loc[0, "query"],
    "description": description,
    "skills": found_skills,
    "skills_count": skills_count
}

In [194]:
print(job_data)

{'title': 'Data Scientist', 'company': 'Ventra', 'address': 'Москва', 'experience': 'Опыт 1-3 года', 'url': 'https://hh.ru/vacancy/136311467?query=Data+Scientist', 'query': 'Data Scientist', 'description': 'Требования: От 2 лет коммерческого опыта запуска дата-продуктов в продуктивной среде. Высшее образование и соответствующий опыт в области статистики, математики, информатики или смежных областях. Уверенное знание SQL, Python (pandas, numpy, scikit-learn, LightGBM/XGBoost) алгоритмов машинного обучения и статистики, опыт с Prophet, statsmodels. Глубокое понимание методов прогнозирования временных рядов. Умение выбирать и обосновывать метрики качества и бизнес-метрики. Опыт создания E2E пайплайнов ML. Подтвержденный опыт создания пайплайнов машинного обучения, работающих в продуктивной среде разработки. Опыт визуализации данных с использованием Power BI/ggplot/plotly/etc. Опыт использования облачных платформ для решения задач дата- аналитики и и запуска моделей машинного обучения в продуктивной среде. Опыт работы со стеком Yandex Cloud Platform – будет плюсом. Опыт работы с GitLab или его аналогами. Опыт работы с Airflow/Docker/Kubernetes или их аналогами. Опыт инференса моделей в MLFlow/Triton или аналогах. Средний или выше среднего уровень знания английского языка. Обязанности и ожидаемые результаты работы: Взаимодействие с бизнес-подразделениями для выявления точек роста и постановки задач на прогнозирование. E2E процесс запуска дата-продуктов в Yandex Cloud Platform. Представлять результаты моделирования для бизнес-аудитории, включая руководителей организации. Превращать неструктурированные недостатки и болевые точки в конкретные бизнес и технические требования для проверки гипотез или разработки дата-продуктов. Мы предлагаем: Официальное трудоустройство по ТК РФ; Возможность развития в рамках крупнейшей FMCG-компании; Конкурентный уровень заработной платы; Удаленный формат работы; Предоставление корпоративной техники.', 'skills': ['Python', 'SQL', 'pandas', 'numpy', 'scikit-learn', 'LightGBM', 'XGBoost', 'Docker', 'Kubernetes', 'Kubernetes'], 'skills_count': 10}

In [195]:
description_tag = job_soup.find(
    attrs={"data-qa": "vacancy-description"}
)

description = (
    description_tag.get_text(" ", strip=True)
    if description_tag
    else None
)

print(description[:1000])

Требования: От 2 лет коммерческого опыта запуска дата-продуктов в продуктивной среде. Высшее образование и соответствующий опыт в области статистики, математики, информатики или смежных областях. Уверенное знание SQL, Python (pandas, numpy, scikit-learn, LightGBM/XGBoost) алгоритмов машинного обучения и статистики, опыт с Prophet, statsmodels. Глубокое понимание методов прогнозирования временных рядов. Умение выбирать и обосновывать метрики качества и бизнес-метрики. Опыт создания E2E пайплайнов ML. Подтвержденный опыт создания пайплайнов машинного обучения, работающих в продуктивной среде разработки. Опыт визуализации данных с использованием Power BI/ggplot/plotly/etc. Опыт использования облачных платформ для решения задач дата- аналитики и и запуска моделей машинного обучения в продуктивной среде. Опыт работы со стеком Yandex Cloud Platform – будет плюсом. Опыт работы с GitLab или его аналогами. Опыт работы с Airflow/Docker/Kubernetes или их аналогами. Опыт инференса моделей в MLFlow

In [196]:
skills = [
    "Python",
    "SQL",
    "pandas",
    "numpy",
    "scikit-learn",
    "LightGBM",
    "XGBoost",
    "PyTorch",
    "TensorFlow",
    "Docker",
    "Kubernetes"
]

found_skills = []

for skill in skills:
    if skill.lower() in description.lower():
        found_skills.append(skill)

print(found_skills)
print("Количество технологий:", len(found_skills))

['Python', 'SQL', 'pandas', 'numpy', 'scikit-learn', 'LightGBM', 'XGBoost', 'Docker', 'Kubernetes']
Количество технологий: 9

In [197]:
import time

In [198]:
def get_vacancy_description(url):
    response = requests.get(
        url,
        headers=headers,
        timeout=20
    )

    if response.status_code != 200:
        return None

    soup = BeautifulSoup(
        response.text,
        "html.parser"
    )

    description_tag = soup.find(
        attrs={"data-qa": "vacancy-description"}
    )

    if description_tag is None:
        return None

    description = description_tag.get_text(
        " ",
        strip=True
    )

    return description

In [200]:
response = requests.get(
    url,
    headers=headers,
    timeout=20
)
response.status_code

200

In [201]:
soup = BeautifulSoup(
    response.text,
    "html.parser"
)

In [203]:
description_tag = soup.find(
    attrs={"data-qa": "vacancy-description"}
)
description_tag

<div class="vacancy-branded-user-content" data-qa="vacancy-description" itemprop="description"><p><strong>Стажировка в МТС </strong>— это твой шанс получить реальный опыт в сильной компании. Начать можно с любого месяца! Ты прокачаешь свои навыки в настоящих проектах и будешь учиться у профессионалов, а по итогам стажировки мы сможем предложить тебе оффер</p> <p><strong>Rоманда</strong> <strong>индивидуального подбора МТС</strong> в поисках боевой единицы, которая будет помогать закрывать такие позиции, как:<em> аналитики (бизнес-аналитики, системные аналитики, аналитики данных, <span class="highlighted">Data</span> <span class="highlighted">Scientists</span>, ML инженеры и т.д.), эксперты технического блока, ИБ, разработчики (Devops, GO\Python\С++ разработчики и тд), проджекты, стратеги, эксперты по клиентскому опыту.</em></p> <p>Если ты любишь расследовать сложные загадки рынка, любишь докопаться до сути, структурно мыслишь, нацелен на результат и перевыполнение плана, любишь настолки, квесты и мемасики, то наша вакансия создана именно для тебя.</p> <p><strong>ЧЕМ ПРЕДСТОИТ ЗАНИМАТЬСЯ:</strong></p> <ul> <li> <p>знакомиться с процессом точечного подбора персонала;</p> </li> <li> <p>учиться искать резюме профессионалов своего дела на работных сайтах и альтернативных источниках;</p> </li> <li> <p>проводить телефонный скрининг или контакт с кандидатом через мессенджеры для проверки ключевых критериев;</p> </li> <li> <p>формировать пул теплых лидов по вакансиям.</p> </li> </ul> <p><strong>ЧТО МЫ ЖДЕМ:</strong></p> <ul> <li>владеешь теоретическими знаниями в HR/Рекрутменте;</li> <li> <p>готов работать <strong>40 часов в неделю</strong>, 3 дня в офисе, 2 удаленно;</p> </li> <li> <p>умеешь работать как в команде, так и самостоятельно;</p> </li> <li> <p>любишь искать информацию и общаться с новыми людьми.</p> </li> </ul> <p><strong>ЧТО МЫ ПРЕДЛАГАЕМ:</strong></p> <ul> <li>гибкий график (40 часов в неделю);</li> <li>комфортный офис в шаговой доступности от ст. м. Марксистская;</li> <li>возможен гибридный формат с посещением офиса;</li> <li>стажировка оплачивается, продолжительность от 6 месяцев (срок обсуждается);</li> <li>возможность быстрее двигаться по карьерной лестнице для стажеров, которые показали высокие результаты и готовы решать сложные задачи самостоятельно;</li> <li>корпоративный тариф связи "Smart для своих"</li> <li>быстроразвивающаяся дружелюбная культура;</li> <li>если все, что ты прочитал - про тебя, то напиши в тг @Allyndiy</li> </ul></div>

In [204]:
test_url = df.loc[0, "url"]

test_description = get_vacancy_description(test_url)

print(test_description[:1000])

Требования: От 2 лет коммерческого опыта запуска дата-продуктов в продуктивной среде. Высшее образование и соответствующий опыт в области статистики, математики, информатики или смежных областях. Уверенное знание SQL, Python (pandas, numpy, scikit-learn, LightGBM/XGBoost) алгоритмов машинного обучения и статистики, опыт с Prophet, statsmodels. Глубокое понимание методов прогнозирования временных рядов. Умение выбирать и обосновывать метрики качества и бизнес-метрики. Опыт создания E2E пайплайнов ML. Подтвержденный опыт создания пайплайнов машинного обучения, работающих в продуктивной среде разработки. Опыт визуализации данных с использованием Power BI/ggplot/plotly/etc. Опыт использования облачных платформ для решения задач дата- аналитики и и запуска моделей машинного обучения в продуктивной среде. Опыт работы со стеком Yandex Cloud Platform – будет плюсом. Опыт работы с GitLab или его аналогами. Опыт работы с Airflow/Docker/Kubernetes или их аналогами. Опыт инференса моделей в MLFlow

In [205]:
for url in df["url"].head(3):
    description = get_vacancy_description(url)

    print("URL:", url)

    if description:
        print(description[:300])
    else:
        print("Описание не найдено")

    print("-" * 80)

    time.sleep(1)

URL: https://hh.ru/vacancy/136311467?query=Data+Scientist
Требования: От 2 лет коммерческого опыта запуска дата-продуктов в продуктивной среде. Высшее образование и соответствующий опыт в области статистики, математики, информатики или смежных областях. Уверенное знание SQL, Python (pandas, numpy, scikit-learn, LightGBM/XGBoost) алгоритмов машинного обучен
--------------------------------------------------------------------------------
URL: https://hh.ru/vacancy/136327913?query=Data+Scientist
О роли Ищем дата-сайентиста, который хочет не просто строить модели, а видеть их реальный эффект на бизнес. Вы будете разрабатывать модели для малайзийского направления, а основным заказчиком станет портфельный менеджер - то есть решения будут напрямую влиять на управление портфелем и бизнес-результ
--------------------------------------------------------------------------------
URL: https://hh.ru/vacancy/136021202?query=Data+Scientist
Ключевые задачи: Сбор, очистка и предобработка текстовых данных для баз знаний RAG-систем (парсинг PDF/DOCX/HTML, чанкинг, нормализация) Разметка и валидация данных, подготовка тестовых наборов для оценки качества ответов LLM Прогон экспериментов по заданным гипотезам, оформление результатов в виде
--------------------------------------------------------------------------------

In [206]:
descriptions = []

for url in df["url"]:
    description = get_vacancy_description(url)

    descriptions.append(description)

    time.sleep(1)

In [207]:
print(len(df))
print(len(descriptions))

20
20

In [208]:
df["description"] = descriptions

In [210]:
df["description"].isna().sum()

np.int64(0)

In [214]:
df['description']

0     Требования: От 2 лет коммерческого опыта запус...
1     О роли Ищем дата-сайентиста, который хочет не ...
2     Ключевые задачи: Сбор, очистка и предобработка...
3     Перед кандидатом мы ставим следующие задачи: С...
4     Группа компаний «HBM» — неизменно высокое каче...
5     Zunami — разработчик и интегратор ИТ решений д...
6     AI/ML Engineer (Инженер искусственного интелле...
7     Привет! Я Григорий, технический руководитель о...
8     Мы в поиске опытного Разработчика на Python го...
9     Вы подойдёте нам, если сможете реализовывать с...
10    Мы ищем Fullstack аналитика для активного учас...
11    Ваши основные задачи: Разработка и внедрение A...
12    Ищем Middle+/Senior Data Scientist . Команда с...
13    Мы ищем специалиста, который поможет развивать...
14    We are looking for a Data Scientist in Poland ...
15    Основные задачи Мониторинг качества прогнозов ...
16    Мы ищем ML-специалиста уровня Junior/Middle дл...
17    Paper Planes — управленческий консалтинг Мы ищ...
18    Группа модельных рисков ForteBank сейчас актив...
19    Стажировка в МТС — это твой шанс получить реал...
Name: description, dtype: str

In [215]:
SKILLS = {
    "python": ["python"],
    "sql": ["sql"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "scikit_learn": ["scikit-learn", "sklearn"],
    "pytorch": ["pytorch"],
    "tensorflow": ["tensorflow"],
    "keras": ["keras"],
    "xgboost": ["xgboost"],
    "lightgbm": ["lightgbm"],
    "catboost": ["catboost"],
    "docker": ["docker"],
    "kubernetes": ["kubernetes", "k8s"],
    "airflow": ["airflow"],
    "spark": ["apache spark", "spark"],
    "kafka": ["kafka"],
    "postgresql": ["postgresql", "postgres"],
    "clickhouse": ["clickhouse"],
    "mongodb": ["mongodb"],
    "git": ["git"],
    "fastapi": ["fastapi"]
}

In [216]:
def extract_skills(description):
    if description is None:
        return []

    text = description.lower()

    found_skills = []

    for skill, variants in SKILLS.items():
        for variant in variants:
            if variant in text:
                found_skills.append(skill)
                break

    return found_skills

In [219]:
skills_test = extract_skills(
    df.loc[0, "description"]
)

print(skills_test)
print(len(skills_test))

['python', 'sql', 'pandas', 'numpy', 'scikit_learn', 'xgboost', 'lightgbm', 'docker', 'kubernetes', 'airflow', 'git']
11

In [218]:
len(skills)

11

In [220]:
df["skills"] = df["description"].apply(
    extract_skills
)

In [221]:
df["skills_count"] = df["skills"].apply(len)

In [223]:
df.head()

,title,company,address,experience,url,query,description,skills,skills_count
0,Data Scientist,Ventra,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136311467?query=Data+Sci...,Data Scientist,Требования: От 2 лет коммерческого опыта запус...,"[python, sql, pandas, numpy, scikit_learn, xgb...",11
1,Data Scientist,ООО Ок Софт,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136327913?query=Data+Sci...,Data Scientist,"О роли Ищем дата-сайентиста, который хочет не ...","[python, sql, pandas, scikit_learn]",4
2,Стажер Data scientist,"ПАО Банк ПСБ, Старт карьеры",Москва,Без опыта,https://hh.ru/vacancy/136021202?query=Data+Sci...,Data Scientist,"Ключевые задачи: Сбор, очистка и предобработка...","[python, docker, git, fastapi]",4
3,Системный аналитик,АО Просвещение,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/136292099?query=Data+Sci...,Data Scientist,Перед кандидатом мы ставим следующие задачи: С...,[sql],1
4,Аналитик данных (Data Scientist),Группа компаний НВМ,"Краснодар, р-н Прикубанский",Опыт 1-3 года,https://hh.ru/vacancy/136265966?query=Data+Sci...,Data Scientist,Группа компаний «HBM» — неизменно высокое каче...,[sql],1

In [224]:
df[
    [
        "title",
        "experience",
        "skills",
        "skills_count"
    ]
].head(10)

,title,experience,skills,skills_count
0,Data Scientist,Опыт 1-3 года,"[python, sql, pandas, numpy, scikit_learn, xgb...",11
1,Data Scientist,Опыт 1-3 года,"[python, sql, pandas, scikit_learn]",4
2,Стажер Data scientist,Без опыта,"[python, docker, git, fastapi]",4
3,Системный аналитик,Опыт 3-6 лет,[sql],1
4,Аналитик данных (Data Scientist),Опыт 1-3 года,[sql],1
5,Data Scientist - стажер,Без опыта,"[python, pandas, numpy, scikit_learn, docker, ...",6
6,ИИ специалист,Опыт 1-3 года,"[python, sql, pandas, numpy, scikit_learn, pyt...",10
7,Junior Data Scientist (Pricing),Без опыта,"[python, sql, pandas, airflow]",4
8,Python/DS специалист (Middle),Опыт 3-6 лет,"[python, sql, pandas, numpy, docker, kubernete...",8
9,Ведущий разработчик искусственного интеллекта/...,Опыт 1-3 года,"[python, pytorch, docker, postgresql, git, fas...",6

In [225]:
skill_columns = list(SKILLS.keys())

print(skill_columns)

['python', 'sql', 'pandas', 'numpy', 'scikit_learn', 'pytorch', 'tensorflow', 'keras', 'xgboost', 'lightgbm', 'catboost', 'docker', 'kubernetes', 'airflow', 'spark', 'kafka', 'postgresql', 'clickhouse', 'mongodb', 'git', 'fastapi']

In [226]:
for skill in skill_columns:
    df[skill] = df["skills"].apply(
        lambda found_skills: 1 if skill in found_skills else 0
    )

In [227]:
df[
    [
        "title",
        "query",
        "skills_count",
        "python",
        "sql",
        "pandas",
        "pytorch",
        "docker"
    ]
].head(10)

,title,query,skills_count,python,sql,pandas,pytorch,docker
0,Data Scientist,Data Scientist,11,1,1,1,0,1
1,Data Scientist,Data Scientist,4,1,1,1,0,0
2,Стажер Data scientist,Data Scientist,4,1,0,0,0,1
3,Системный аналитик,Data Scientist,1,0,1,0,0,0
4,Аналитик данных (Data Scientist),Data Scientist,1,0,1,0,0,0
5,Data Scientist - стажер,Data Scientist,6,1,0,1,0,1
6,ИИ специалист,Data Scientist,10,1,1,1,1,1
7,Junior Data Scientist (Pricing),Data Scientist,4,1,1,1,0,0
8,Python/DS специалист (Middle),Data Scientist,8,1,1,1,0,1
9,Ведущий разработчик искусственного интеллекта/...,Data Scientist,6,1,0,0,1,1

In [228]:
skill_frequency = df[skill_columns].sum()

print(skill_frequency)

python          15
sql             12
pandas           9
numpy            6
scikit_learn     7
pytorch          3
tensorflow       2
keras            0
xgboost          2
lightgbm         2
catboost         1
docker           7
kubernetes       3
airflow          5
spark            4
kafka            1
postgresql       4
clickhouse       1
mongodb          0
git              8
fastapi          4
dtype: int64

In [229]:
skill_frequency = (
    df[skill_columns]
    .sum()
    .sort_values(ascending=False)
)

print(skill_frequency)

python          15
sql             12
pandas           9
git              8
scikit_learn     7
docker           7
numpy            6
airflow          5
postgresql       4
spark            4
fastapi          4
kubernetes       3
pytorch          3
tensorflow       2
lightgbm         2
xgboost          2
catboost         1
clickhouse       1
kafka            1
keras            0
mongodb          0
dtype: int64

In [230]:
skill_percent = (
    df[skill_columns]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(skill_percent)

python          75.0
sql             60.0
pandas          45.0
git             40.0
scikit_learn    35.0
docker          35.0
numpy           30.0
airflow         25.0
postgresql      20.0
spark           20.0
fastapi         20.0
kubernetes      15.0
pytorch         15.0
tensorflow      10.0
lightgbm        10.0
xgboost         10.0
catboost         5.0
clickhouse       5.0
kafka            5.0
keras            0.0
mongodb          0.0
dtype: float64

In [231]:
query = "Data Scientist"

In [232]:
def collect_search_page(query):
    url = "https://rabota.by/search/vacancy"

    params = {
        "text": query
    }

    response = requests.get(
        url,
        params=params,
        headers=headers,
        timeout=20
    )

    if response.status_code != 200:
        print(
            f"Ошибка для {query}:",
            response.status_code
        )
        return []

    soup = BeautifulSoup(
        response.text,
        "html.parser"
    )

    cards = soup.find_all(
        "article",
        attrs={"data-qa": "vacancy-serp__vacancy"}
    )

    jobs = []

    for card in cards:

        title_tag = card.find(
            "a",
            attrs={"data-qa": "serp-item__title"}
        )

        company_tag = card.find(
            attrs={
                "data-qa":
                "vacancy-serp__vacancy-employer"
            }
        )

        address_tag = card.find(
            attrs={
                "data-qa":
                "vacancy-serp__vacancy-address"
            }
        )

        experience_tag = card.select_one(
            '[data-qa^="vacancy-serp__vacancy-work-experience"]'
        )

        title = (
            title_tag.get_text(" ", strip=True)
            if title_tag
            else None
        )

        url = (
            title_tag.get("href")
            if title_tag
            else None
        )

        company = (
            company_tag.get_text(" ", strip=True)
            if company_tag
            else None
        )

        address = (
            address_tag.get_text(" ", strip=True)
            if address_tag
            else None
        )

        experience = (
            experience_tag.get_text(" ", strip=True)
            if experience_tag
            else None
        )

        job = {
            "title": title,
            "company": company,
            "address": address,
            "experience": experience,
            "url": url,
            "query": query
        }

        jobs.append(job)

    return jobs

In [233]:
test_jobs = collect_search_page(
    "ML Engineer"
)

print(len(test_jobs))
print(test_jobs[:2])

20
[{'title': 'AI инженер', 'company': 'S7 Group', 'address': 'Москва', 'experience': 'Опыт 1-3 года', 'url': 'https://hh.ru/vacancy/136342152?query=ML+Engineer', 'query': 'ML Engineer'}, {'title': 'AI-Engineer', 'company': 'ТОО Armeta KZ', 'address': 'Астана, улица Сыганак, 60/2', 'experience': 'Опыт 1-3 года', 'url': 'https://hh.ru/vacancy/136340212?query=ML+Engineer', 'query': 'ML Engineer'}]

In [234]:
QUERIES = [
    "Data Analyst",
    "Data Scientist",
    "ML Engineer",
    "Data Engineer",
    "MLOps"
]

In [236]:
all_jobs = []

for query in QUERIES:
    print("Собираю:", query)

    query_jobs = collect_search_page(query)

    all_jobs.extend(query_jobs)

    print(
        "Получено:",
        len(query_jobs)
    )

    time.sleep(1)

Собираю: Data Analyst
Получено: 20
Собираю: Data Scientist
Получено: 20
Собираю: ML Engineer
Получено: 20
Собираю: Data Engineer
Получено: 20
Собираю: MLOps
Получено: 20

In [237]:
df_all = pd.DataFrame(all_jobs)

print(df_all.shape)

display(
    df_all[
        [
            "title",
            "query",
            "company",
            "experience",
            "address"
        ]
    ].head(20)
)

(100, 6)

,title,query,company,experience,address
0,Senior Python Backend Developer R&D Engineer,Data Analyst,Altezza Travelling LTD,Опыт 3-6 лет,Моши
1,Младший биоинформатик-аналитик,Data Analyst,ООО Парсек Лаб,Опыт 1-3 года,"Санкт-Петербург, р-н Приморский"
2,Data Ananlyst / Аналитик Данных,Data Analyst,Ventra,Опыт 1-3 года,Москва
3,Бизнес-аналитик,Data Analyst,Группа Компаний «Аскона» | Логистика,Опыт 3-6 лет,Москва
4,Аналитик данных,Data Analyst,RUTUBE,Опыт 1-3 года,Москва
5,Системный аналитик (FinTech / Crypto / Blockch...,Data Analyst,ООО Веро Трейс,Опыт 3-6 лет,Москва
6,Бэкенд-разработчик (java),Data Analyst,ООО ЛИПТ Софт,Опыт более 6 лет,Санкт-Петербург
7,Специалист по управлению данными / Аналитик да...,Data Analyst,ООО Бюро Цифровой Трансформации,Опыт 1-3 года,Москва
8,Аналитик данных (Power BI),Data Analyst,TraffCloud,Опыт 3-6 лет,Москва
9,Заместитель директора по маркетингу,Data Analyst,ООО Имбрык,Опыт 3-6 лет,Минск
10,Руководитель аналитики данных,Data Analyst,ООО Альфа-Мобайл,Опыт 3-6 лет,Москва
11,Бизнес-аналитик,Data Analyst,"""МТС"", Аналитика",Опыт 1-3 года,Москва
12,Системный аналитик Middle/Senior,Data Analyst,.redev,Опыт 3-6 лет,Москва
13,Product Manager в команду Core,Data Analyst,АО Kolesa (АО Колеса),Опыт 3-6 лет,Алматы
14,Data Scientist,Data Analyst,Ventra,Опыт 1-3 года,Москва
15,Финансовый директор (CFO),Data Analyst,СберСпасибо,Опыт более 6 лет,"Москва, р-н Дорогомилово"
16,Системный аналитик,Data Analyst,ЛИАН,Опыт 3-6 лет,Москва
17,Руководитель отдела персонала (HRD/HRBP),Data Analyst,IN HOUSE,Опыт 3-6 лет,Москва
18,Бизнес-аналитик,Data Analyst,ООО Майфин,Опыт 3-6 лет,Минск
19,Инженер сопровождения,Data Analyst,ЛИАН,Опыт 3-6 лет,Москва

In [238]:
skill_columns = list(SKILLS.keys())

for skill in skill_columns:
    df[skill] = df["skills"].apply(
        lambda found_skills: 1 if skill in found_skills else 0
    )

In [239]:
skill_percent = (
    df[skill_columns]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(skill_percent)

python          75.0
sql             60.0
pandas          45.0
git             40.0
scikit_learn    35.0
docker          35.0
numpy           30.0
airflow         25.0
postgresql      20.0
spark           20.0
fastapi         20.0
kubernetes      15.0
pytorch         15.0
tensorflow      10.0
lightgbm        10.0
xgboost         10.0
catboost         5.0
clickhouse       5.0
kafka            5.0
keras            0.0
mongodb          0.0
dtype: float64

In [240]:
test_jobs = collect_search_page(
    "ML Engineer"
)

print("Найдено:", len(test_jobs))

for job in test_jobs[:5]:
    print(job["title"])

Найдено: 20
AI инженер
AI-Engineer
QA Engineer / Тестировщик программного обеспечения
Middle QA Engineer
QA Engineer (Middle)

In [241]:
def collect_search_page(query, page=0):
    url = "https://rabota.by/search/vacancy"

    params = {
        "text": query,
        "page": page
    }

    response = requests.get(
        url,
        params=params,
        headers=headers,
        timeout=20
    )

    if response.status_code != 200:
        print(
            f"Ошибка для {query}, страница {page}:",
            response.status_code
        )
        return []

    soup = BeautifulSoup(
        response.text,
        "html.parser"
    )

    cards = soup.find_all(
        "article",
        attrs={"data-qa": "vacancy-serp__vacancy"}
    )

    jobs = []

    for card in cards:

        title_tag = card.find(
            "a",
            attrs={"data-qa": "serp-item__title"}
        )

        company_tag = card.find(
            attrs={
                "data-qa": "vacancy-serp__vacancy-employer"
            }
        )

        address_tag = card.find(
            attrs={
                "data-qa": "vacancy-serp__vacancy-address"
            }
        )

        experience_tag = card.select_one(
            '[data-qa^="vacancy-serp__vacancy-work-experience"]'
        )

        title = (
            title_tag.get_text(" ", strip=True)
            if title_tag
            else None
        )

        vacancy_url = (
            title_tag.get("href")
            if title_tag
            else None
        )

        company = (
            company_tag.get_text(" ", strip=True)
            if company_tag
            else None
        )

        address = (
            address_tag.get_text(" ", strip=True)
            if address_tag
            else None
        )

        experience = (
            experience_tag.get_text(" ", strip=True)
            if experience_tag
            else None
        )

        job = {
            "title": title,
            "company": company,
            "address": address,
            "experience": experience,
            "url": vacancy_url,
            "query": query,
            "page": page
        }

        jobs.append(job)

    return jobs

In [242]:
page_0 = collect_search_page(
    "Data Scientist",
    page=0
)

page_1 = collect_search_page(
    "Data Scientist",
    page=1
)

print("Страница 0:", len(page_0))
print("Страница 1:", len(page_1))

Страница 0: 20
Страница 1: 20

In [243]:
print(page_0[0]["title"])
print(page_1[0]["title"])

Data Scientist
Data Science Engineer / Инженер по анализу данных / Инженер по машинному обучению /

In [244]:
QUERIES = [
    "Data Analyst",
    "BI Analyst",
    "Data Scientist",
    "ML Engineer",
    "Data Engineer",
    "MLOps",
    "AI Engineer",
    "Python Developer"
]

In [245]:
PAGES_PER_QUERY = 10

In [246]:
all_jobs = []

for query in QUERIES:

    print()
    print("Запрос:", query)

    for page in range(PAGES_PER_QUERY):

        print(
            "  Страница:",
            page
        )

        page_jobs = collect_search_page(
            query,
            page=page
        )

        print(
            "  Получено:",
            len(page_jobs)
        )

        all_jobs.extend(page_jobs)

        time.sleep(1)

Запрос: Data Analyst
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 20
  Страница: 6
  Получено: 20
  Страница: 7
  Получено: 20
  Страница: 8
  Получено: 20
  Страница: 9
  Получено: 20

Запрос: BI Analyst
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 20
  Страница: 6
  Получено: 20
  Страница: 7
  Получено: 20
  Страница: 8
  Получено: 20
  Страница: 9
  Получено: 20

Запрос: Data Scientist
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 11
  Страница: 6
  Получено: 0
  Страница: 7
  Получено: 0
  Страница: 8
  Получено: 0
  Страница: 9
  Получено: 0

Запрос: ML Engineer
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 20
  Страница: 6
  Получено: 20
  Страница: 7
  Получено: 20
  Страница: 8
  Получено: 20
  Страница: 9
  Получено: 20

Запрос: Data Engineer
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 20
  Страница: 6
  Получено: 20
  Страница: 7
  Получено: 20
  Страница: 8
  Получено: 20
  Страница: 9
  Получено: 20

Запрос: MLOps
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 20
  Страница: 6
  Получено: 0
  Страница: 7
  Получено: 0
  Страница: 8
  Получено: 0
  Страница: 9
  Получено: 0

Запрос: AI Engineer
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 20
  Страница: 6
  Получено: 20
  Страница: 7
  Получено: 20
  Страница: 8
  Получено: 20
  Страница: 9
  Получено: 20

Запрос: Python Developer
  Страница: 0
  Получено: 20
  Страница: 1
  Получено: 20
  Страница: 2
  Получено: 20
  Страница: 3
  Получено: 20
  Страница: 4
  Получено: 20
  Страница: 5
  Получено: 20
  Страница: 6
  Получено: 20
  Страница: 7
  Получено: 20
  Страница: 8
  Получено: 20
  Страница: 9
  Получено: 20

In [247]:
SKILLS = {

    # -------------------------
    # Programming
    # -------------------------
    "python": [
        "python"
    ],

    "r": [
        " r ",
        "r language",
        "язык r"
    ],

    "java": [
        "java"
    ],

    "scala": [
        "scala"
    ],

    "cpp": [
        "c++"
    ],


    # -------------------------
    # Data analysis
    # -------------------------
    "pandas": [
        "pandas"
    ],

    "numpy": [
        "numpy"
    ],

    "scipy": [
        "scipy"
    ],

    "statsmodels": [
        "statsmodels"
    ],


    # -------------------------
    # Visualization
    # -------------------------
    "matplotlib": [
        "matplotlib"
    ],

    "seaborn": [
        "seaborn"
    ],

    "plotly": [
        "plotly"
    ],


    # -------------------------
    # BI
    # -------------------------
    "power_bi": [
        "power bi",
        "powerbi"
    ],

    "tableau": [
        "tableau"
    ],

    "excel": [
        "excel",
        "ms excel",
        "microsoft excel"
    ],

    "power_query": [
        "power query"
    ],

    "dax": [
        "dax"
    ],

    "looker": [
        "looker",
        "looker studio"
    ],

    "qlik": [
        "qlik",
        "qlik sense",
        "qlikview"
    ],

    "metabase": [
        "metabase"
    ],


    # -------------------------
    # SQL / Databases
    # -------------------------
    "sql": [
        "sql"
    ],

    "postgresql": [
        "postgresql",
        "postgres"
    ],

    "mysql": [
        "mysql"
    ],

    "ms_sql_server": [
        "mssql",
        "ms sql",
        "ms sql server",
        "microsoft sql server",
        "sql server"
    ],

    "oracle": [
        "oracle database",
        "oracle db"
    ],

    "clickhouse": [
        "clickhouse"
    ],

    "mongodb": [
        "mongodb",
        "mongo db"
    ],

    "redis": [
        "redis"
    ],

    "sqlite": [
        "sqlite"
    ],


    # -------------------------
    # Classical Machine Learning
    # -------------------------
    "scikit_learn": [
        "scikit-learn",
        "scikit learn",
        "sklearn"
    ],

    "xgboost": [
        "xgboost"
    ],

    "lightgbm": [
        "lightgbm",
        "light gbm"
    ],

    "catboost": [
        "catboost"
    ],


    # -------------------------
    # Deep Learning
    # -------------------------
    "pytorch": [
        "pytorch",
        "torch"
    ],

    "tensorflow": [
        "tensorflow"
    ],

    "keras": [
        "keras"
    ],


    # -------------------------
    # Computer Vision
    # -------------------------
    "opencv": [
        "opencv",
        "open cv"
    ],

    "yolo": [
        "yolo"
    ],


    # -------------------------
    # NLP / LLM
    # -------------------------
    "nlp": [
        "nlp",
        "natural language processing"
    ],

    "transformers": [
        "transformers"
    ],

    "huggingface": [
        "hugging face",
        "huggingface"
    ],

    "llm": [
        "llm",
        "large language model",
        "large language models"
    ],

    "rag": [
        "rag",
        "retrieval augmented generation",
        "retrieval-augmented generation"
    ],

    "langchain": [
        "langchain"
    ],

    "llamaindex": [
        "llamaindex",
        "llama index"
    ],

    "openai_api": [
        "openai api"
    ],


    # -------------------------
    # Big Data / Data Engineering
    # -------------------------
    "spark": [
        "apache spark",
        "pyspark",
        "spark"
    ],

    "hadoop": [
        "hadoop"
    ],

    "kafka": [
        "apache kafka",
        "kafka"
    ],

    "airflow": [
        "apache airflow",
        "airflow"
    ],

    "dbt": [
        "dbt",
        "data build tool"
    ],

    "hive": [
        "apache hive",
        "hive"
    ],

    "snowflake": [
        "snowflake"
    ],

    "bigquery": [
        "bigquery",
        "big query"
    ],

    "databricks": [
        "databricks"
    ],


    # -------------------------
    # MLOps / DevOps
    # -------------------------
    "docker": [
        "docker"
    ],

    "kubernetes": [
        "kubernetes",
        "k8s"
    ],

    "mlflow": [
        "mlflow"
    ],

    "dvc": [
        "dvc",
        "data version control"
    ],

    "git": [
        "git"
    ],

    "github": [
        "github"
    ],

    "gitlab": [
        "gitlab"
    ],

    "jenkins": [
        "jenkins"
    ],

    "ci_cd": [
        "ci/cd",
        "ci cd",
        "continuous integration"
    ],


    # -------------------------
    # Cloud
    # -------------------------
    "aws": [
        "aws",
        "amazon web services"
    ],

    "azure": [
        "microsoft azure",
        "azure"
    ],

    "gcp": [
        "gcp",
        "google cloud",
        "google cloud platform"
    ],


    # -------------------------
    # Backend / API
    # -------------------------
    "fastapi": [
        "fastapi",
        "fast api"
    ],

    "flask": [
        "flask"
    ],

    "django": [
        "django"
    ],

    "rest_api": [
        "rest api",
        "restful",
        "rest-api"
    ],


    # -------------------------
    # Other analytics tools
    # -------------------------
    "jupyter": [
        "jupyter",
        "jupyter notebook"
    ],

    "notebook": [
        "notebook"
    ],

    "sas": [
        "sas"
    ],

    "spss": [
        "spss"
    ]
}

In [ ]:
# начало встречаться часто r и другие буквы в скиллах, надо регулярные выражения добавить
import re
def extract_skills(description):

    if description is None:
        return []

    text = description.lower()

    found_skills = []

    for skill, variants in SKILLS.items():

        for variant in variants:

            pattern = (#непосредственно до и после найденной технологии не должно быть буквы, цифры
                r"(?<!\w)"
                + re.escape(variant.lower().strip())
                + r"(?!\w)"
            )

            if re.search(pattern, text):
                found_skills.append(skill)
                break

    return found_skills

In [254]:
all_jobs

[{'title': 'Младший биоинформатик-аналитик',
  'company': 'ООО Парсек Лаб',
  'address': 'Санкт-Петербург, р-н Приморский',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135719646?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Data Ananlyst / Аналитик Данных',
  'company': 'Ventra',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136031153?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Бизнес-аналитик',
  'company': 'Группа Компаний «Аскона» | Логистика',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136361346?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Системный аналитик (FinTech / Crypto / Blockchain)',
  'company': 'ООО Веро Трейс',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135661700?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Аналитик данных',
  'company': 'RUTUBE',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136365089?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Специалист по управлению данными / Аналитик данных (Data Analyst/Data Engineer)',
  'company': 'ООО Бюро Цифровой Трансформации',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136299705?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Бэкенд-разработчик (java)',
  'company': 'ООО ЛИПТ Софт',
  'address': 'Санкт-Петербург',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136330740?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Аналитик данных (Power BI)',
  'company': 'TraffCloud',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136329784?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Руководитель аналитики данных',
  'company': 'ООО Альфа-Мобайл',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136187215?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Заместитель директора по маркетингу',
  'company': 'ООО Имбрык',
  'address': 'Минск',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://rabota.by/vacancy/136317462?query=Data+Analyst&hhtmFrom=vacancy_search_list',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Бизнес-аналитик',
  'company': '"МТС", Аналитика',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136327869?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Системный аналитик Middle/Senior',
  'company': '.redev',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135664064?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Data Scientist',
  'company': 'Ventra',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136311467?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Product Manager в команду Core',
  'company': 'АО Kolesa (АО Колеса)',
  'address': 'Алматы',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136311981?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Финансовый директор (CFO)',
  'company': 'СберСпасибо',
  'address': 'Москва, р-н Дорогомилово',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136172759?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Системный аналитик',
  'company': 'ЛИАН',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136202014?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Руководитель отдела персонала (HRD/HRBP)',
  'company': 'IN HOUSE',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136245167?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Бизнес-аналитик',
  'company': 'ООО Майфин',
  'address': 'Минск',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://rabota.by/vacancy/136346114?query=Data+Analyst&hhtmFrom=vacancy_search_list',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Инженер сопровождения',
  'company': 'ЛИАН',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136315909?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Java-разработчик',
  'company': 'ООО ВЫСОКИЕ ТЕХНОЛОГИИ ДЛЯ БИЗНЕСА',
  'address': 'Оренбург, р-н Центральный',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136237665?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 0},
 {'title': 'Data Analyst / Аналитик данных',
  'company': 'Генотек',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135117849?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Middle+/Senior Бизнес-/системный аналитик',
  'company': 'ООО SpbDev',
  'address': 'Москва',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/135655138?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'HR-generalist в IT-компанию',
  'company': 'АЭРО',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136265496?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Аналитик данных / Data Analyst (Smartup)',
  'company': 'СП ООО MONO-ELECTRIC',
  'address': 'Ташкент',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136351468?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Продуктовый аналитик',
  'company': 'JapanStat',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136214542?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Директор по информационным технологиям (CIO)',
  'company': 'ТОО КОМЕК МАШИНЕРИ Казахстан',
  'address': 'Астана, проспект Нургисы Тлендиева, 4/3',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136306344?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Бизнес-аналитик',
  'company': 'ООО Газпромнефть-Региональные продажи',
  'address': 'Санкт-Петербург',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136362849?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Java разработчик',
  'company': 'Ингосстрах',
  'address': 'Нижний Новгород',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136259707?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Исполнительный директор (CEO)',
  'company': 'ООО Ритейл Эксперт',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135872574?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'ИИ специалист',
  'company': 'Дверянин',
  'address': 'Набережные Челны, БАЗА ЗАО ,,ПОДРЯД,,, 1',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136266273?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Junior Python-разработчик / технический помощник СТО',
  'company': 'Мегасклад',
  'address': 'Москва',
  'experience': 'Без опыта',
  'url': 'https://hh.ru/vacancy/136267481?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Data engineer (Стажер)',
  'company': 'Sapiens solutions',
  'address': 'Москва',
  'experience': 'Без опыта',
  'url': 'https://hh.ru/vacancy/136125082?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Frontend-разработчик',
  'company': 'Аптечная сеть Ваша №1 х Таблетка.ру',
  'address': 'Москва, р-н Перово',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/128966075?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Product Owner',
  'company': 'ООО Хайерлэб',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136037762?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Системный аналитик / System Analyst',
  'company': 'Aston',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136345328?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Продуктовый дизайнер',
  'company': 'MR Group, группа компаний',
  'address': 'Москва',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136145358?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Ведущий маркетолог',
  'company': 'ТОО Engineering Services',
  'address': 'Алматы',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136334450?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Аналитик продаж',
  'company': 'ООО Газпромнефть-Региональные продажи',
  'address': 'Санкт-Петербург',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136352891?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Middle+ / Senior Data Engineer / ETL-разработчик',
  'company': 'ООО SpbDev',
  'address': 'Москва',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/135655122?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Коммерческий директор / Chief Commercial Officer, CCO',
  'company': 'ООО Стафф Контракт',
  'address': 'Москва',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136117477?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 1},
 {'title': 'Менеджер проектов',
  'company': 'Paper Planes',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136072352?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Strategy & Business Analyst / Бизнес Аналитик',
  'company': 'BlaBlaCar',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136212025?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Младший аналитик данных',
  'company': 'SOKOLOV',
  'address': 'Кострома, р-н Центральный',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135774982?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Java Backend разработчик',
  'company': 'Альфа-Банк. ИТ-специалисты',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135029864?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Data Platform Engineer',
  'company': 'ООО Ритейл Эксперт',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136298963?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Менеджер по корпоративным финансам',
  'company': 'ООО Хевел',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136338546?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'ML-инженер',
  'company': 'МАГНИТ, Розничная сеть. IT',
  'address': 'Москва, р-н Беговой',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136298305?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Системный аналитик Security Vision',
  'company': 'ЛИАН',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136144074?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Старший исследователь продукта (Посуточная аренда жилья)',
  'company': 'Циан',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136348952?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Системный Аналитик',
  'company': 'АО Зарубежнефть',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136358881?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Strong Junior / Middle Risk Quant',
  'company': 'АО ForteBank',
  'address': 'Астана, улица Достык, 8/1',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136173116?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Аналитик данных/Инженер по качеству данных',
  'company': 'X5 Tech',
  'address': 'Москва, р-н Замоскворечье',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136249031?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Инженер-программист C++ \\ QT',
  'company': 'РОСКОСМОС',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136347187?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Product Analyst / Продуктовый аналитик',
  'company': 'Плати по миру',
  'address': 'Москва, р-н Тверской',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136220814?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Middle Аналитик',
  'company': 'Metacommerce',
  'address': 'Уфа',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135767707?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Data analyst - Collection',
  'company': 'UZUM TECHNOLOGIES. IT',
  'address': 'Ташкент, Ферганское шоссе, 23',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136140298?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Стажер аналитик данных / Intern Data Analyst',
  'company': 'Deft',
  'address': 'Москва',
  'experience': 'Без опыта',
  'url': 'https://hh.ru/vacancy/134581924?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Business Analyst',
  'company': 'ООО ПСТ Лабс',
  'address': 'Минск',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://rabota.by/vacancy/136185677?query=Data+Analyst&hhtmFrom=vacancy_search_list',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Системный / Бизнес аналитик',
  'company': 'Altenar',
  'address': 'Екатеринбург',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135206584?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'Маркетолог',
  'company': 'ООО Александровский',
  'address': 'Кемерово, р-н Центральный',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136203865?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 2},
 {'title': 'UX/UI-дизайнер',
  'company': 'Absolut POS',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135537515?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Data Analyst (Middle)',
  'company': 'Polonium Arts',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136034338?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Product Manager / Product Lead',
  'company': 'Airvoice',
  'address': 'Белград, Улица Косте Абрашевића, 13',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136341162?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Data Engineer',
  'company': 'Koronatech',
  'address': 'Санкт-Петербург',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135392614?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Заместитель директора Центра по развитию цифровых решений и аналитических систем',
  'company': 'ФГАОУ ВО Первый МГМУ им. И.М.Сеченова Минздрава России (Сеченовский Университет)',
  'address': 'Москва',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136252925?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Менеджер финансового отдела по автоматизации бизнес-прооцессов',
  'company': 'Наймиум',
  'address': 'Москва, р-н Беговой',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135653465?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Системный аналитик (outstaff)',
  'company': 'ООО Триада',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135374424?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Аналитик данных в технический департамент',
  'company': 'VK',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136263866?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Руководитель проектов (международный проект в банковском секторе)',
  'company': 'USETECH',
  'address': 'Маскат',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136169462?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Research Engineer',
  'company': 'Точка Банк',
  'address': 'Москва, р-н Тверской',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136142033?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'AI Engineer',
  'company': 'АО Цифровой семейный офис',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136031525?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Бизнес аналитик (Математические модели)',
  'company': 'ООО АФЛТ-Системс',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136248879?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Middle backend developer / Python специалист',
  'company': 'Brandquad',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135744558?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Data analyst',
  'company': 'ООО Центр Новых Финансовых Сервисов',
  'address': 'Москва, р-н Дорогомилово',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135540304?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Business Analyst/Systems Analyst',
  'company': 'ТРТ',
  'address': 'Баку',
  'experience': 'Опыт более 6\xa0лет',
  'url': 'https://hh.ru/vacancy/136210954?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Проджект-менеджер',
  'company': 'ТОО Arbuz Group (Арбуз Груп)',
  'address': 'Алматы',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135964906?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Data Analyst DWH (DataVault/Системный аналитик качества данных/Банк)',
  'company': 'Neoflex',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/136319166?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Аналитик данных',
  'company': 'Coleman Group',
  'address': 'Москва',
  'experience': 'Опыт 1-3 года',
  'url': 'https://hh.ru/vacancy/135997211?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Product manager',
  'company': 'Т-Банк. ИТ. Управление продуктами и проектами',
  'address': 'Нижний Новгород',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136330793?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Ведущий аналитик данных',
  'company': 'ГК Дамате',
  'address': 'Москва',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/136214868?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 3},
 {'title': 'Python Developer AI team (в офис, г. Йошкар-Ола)',
  'company': 'TravelLine',
  'address': 'Йошкар-Ола, Комсомольская улица, 112',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135712719?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 4},
 {'title': 'BI-разработчик / Data Analyst Загородный отель, Московская область',
  'company': 'Рябиновый берег',
  'address': 'городской округ Мытищи',
  'experience': 'Опыт 3-6 лет',
  'url': 'https://hh.ru/vacancy/135807248?query=Data+Analyst',
  'query': 'Data Analyst',
  'page': 4},

In [255]:
import pandas as pd

df_raw = pd.DataFrame(all_jobs)

In [256]:
print("Размер:", df_raw.shape)

display(df_raw.head(10))

Размер: (1431, 7)

,title,company,address,experience,url,query,page
0,Младший биоинформатик-аналитик,ООО Парсек Лаб,"Санкт-Петербург, р-н Приморский",Опыт 1-3 года,https://hh.ru/vacancy/135719646?query=Data+Ana...,Data Analyst,0
1,Data Ananlyst / Аналитик Данных,Ventra,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136031153?query=Data+Ana...,Data Analyst,0
2,Бизнес-аналитик,Группа Компаний «Аскона» | Логистика,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/136361346?query=Data+Ana...,Data Analyst,0
3,Системный аналитик (FinTech / Crypto / Blockch...,ООО Веро Трейс,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/135661700?query=Data+Ana...,Data Analyst,0
4,Аналитик данных,RUTUBE,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136365089?query=Data+Ana...,Data Analyst,0
5,Специалист по управлению данными / Аналитик да...,ООО Бюро Цифровой Трансформации,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136299705?query=Data+Ana...,Data Analyst,0
6,Бэкенд-разработчик (java),ООО ЛИПТ Софт,Санкт-Петербург,Опыт более 6 лет,https://hh.ru/vacancy/136330740?query=Data+Ana...,Data Analyst,0
7,Аналитик данных (Power BI),TraffCloud,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/136329784?query=Data+Ana...,Data Analyst,0
8,Руководитель аналитики данных,ООО Альфа-Мобайл,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/136187215?query=Data+Ana...,Data Analyst,0
9,Заместитель директора по маркетингу,ООО Имбрык,Минск,Опыт 3-6 лет,https://rabota.by/vacancy/136317462?query=Data...,Data Analyst,0

In [257]:
print(df_raw["query"].value_counts())

query
Data Analyst        200
BI Analyst          200
ML Engineer         200
Data Engineer       200
AI Engineer         200
Python Developer    200
MLOps               120
Data Scientist      111
Name: count, dtype: int64

In [258]:
print(df_raw.isna().sum())

title         0
company       5
address       0
experience    0
url           0
query         0
page          0
dtype: int64

In [259]:
#выделю id вакансий, чтобы не сравнивать всю ссылку
df_raw["vacancy_id"] = (
    df_raw["url"]
    .str.extract(r"/vacancy/(\d+)")
)

In [260]:
display(
    df_raw[
        ["title", "vacancy_id", "url"]
    ].head()
)

,title,vacancy_id,url
0,Младший биоинформатик-аналитик,135719646,https://hh.ru/vacancy/135719646?query=Data+Ana...
1,Data Ananlyst / Аналитик Данных,136031153,https://hh.ru/vacancy/136031153?query=Data+Ana...
2,Бизнес-аналитик,136361346,https://hh.ru/vacancy/136361346?query=Data+Ana...
3,Системный аналитик (FinTech / Crypto / Blockch...,135661700,https://hh.ru/vacancy/135661700?query=Data+Ana...
4,Аналитик данных,136365089,https://hh.ru/vacancy/136365089?query=Data+Ana...

In [261]:
print(
    "Дубликатов:",
    df_raw["vacancy_id"].duplicated().sum()
)

Дубликатов: 174

In [263]:
matched_queries = (
    df_raw
    .groupby("vacancy_id")["query"] #объединяем строки вакансий, только поисковые запросы
    .agg(lambda x: sorted(set(x))) #удаляем повторяющиеся запросы и сортируем их
    .reset_index(name="matched_queries")
)

In [264]:
df = (
    df_raw
    .drop_duplicates(
        subset=["vacancy_id"],
        keep="first"
    )
    .merge(
        matched_queries,
        on="vacancy_id",
        how="left"
    )
    .reset_index(drop=True)
)

In [266]:
print("До:", len(df_raw))
print("После удаления дублей:", len(df))
len(df_raw)-len(df)

До: 1431
После удаления дублей: 1257

174

In [267]:
df_raw.to_csv(
    "../data/raw/vacancies_search_raw.csv",
    index=False,
    encoding="utf-8-sig"
)

df.to_csv(
    "../data/raw/vacancies_unique.csv",
    index=False,
    encoding="utf-8-sig"
)

In [268]:
session = requests.Session()
session.headers.update(headers)

In [269]:
def get_vacancy_description(url):

    try:
        response = session.get(
            url,
            timeout=20
        )

        response.raise_for_status()

    except requests.RequestException:
        return None

    soup = BeautifulSoup(
        response.text,
        "html.parser"
    )

    description_tag = soup.find(
        attrs={"data-qa": "vacancy-description"}
    )

    if description_tag is None:
        return None

    return description_tag.get_text(
        " ",
        strip=True
    )

In [270]:
descriptions = []

for i, url in enumerate(df["url"]):

    description = get_vacancy_description(url)

    descriptions.append(description)

    if (i + 1) % 20 == 0:
        print(
            f"Обработано {i + 1} из {len(df)}"
        )

    time.sleep(1)

Обработано 20 из 1257
Обработано 40 из 1257
Обработано 60 из 1257
Обработано 80 из 1257
Обработано 100 из 1257
Обработано 120 из 1257
Обработано 140 из 1257
Обработано 160 из 1257
Обработано 180 из 1257
Обработано 200 из 1257
Обработано 220 из 1257
Обработано 240 из 1257
Обработано 260 из 1257
Обработано 280 из 1257
Обработано 300 из 1257
Обработано 320 из 1257
Обработано 340 из 1257
Обработано 360 из 1257
Обработано 380 из 1257
Обработано 400 из 1257
Обработано 420 из 1257
Обработано 440 из 1257
Обработано 460 из 1257
Обработано 480 из 1257
Обработано 500 из 1257
Обработано 520 из 1257
Обработано 540 из 1257
Обработано 560 из 1257
Обработано 580 из 1257
Обработано 600 из 1257
Обработано 620 из 1257
Обработано 640 из 1257
Обработано 660 из 1257
Обработано 680 из 1257
Обработано 700 из 1257
Обработано 720 из 1257
Обработано 740 из 1257
Обработано 760 из 1257
Обработано 780 из 1257
Обработано 800 из 1257
Обработано 820 из 1257
Обработано 840 из 1257
Обработано 860 из 1257
Обработано 880 из 1257
Обработано 900 из 1257
Обработано 920 из 1257
Обработано 940 из 1257
Обработано 960 из 1257
Обработано 980 из 1257
Обработано 1000 из 1257
Обработано 1020 из 1257
Обработано 1040 из 1257
Обработано 1060 из 1257
Обработано 1080 из 1257
Обработано 1100 из 1257
Обработано 1120 из 1257
Обработано 1140 из 1257
Обработано 1160 из 1257
Обработано 1180 из 1257
Обработано 1200 из 1257
Обработано 1220 из 1257
Обработано 1240 из 1257

In [271]:
df["description"] = descriptions

In [272]:
print(
    "Всего:",
    len(df)
)

print(
    "Получено описаний:",
    df["description"].notna().sum()
)

print(
    "Нет описания:",
    df["description"].isna().sum()
)

Всего: 1257
Получено описаний: 1250
Нет описания: 7

In [273]:
df2= descriptions

In [274]:
df["skills"] = (
    df["description"]
    .apply(extract_skills)
)

AttributeError: 'float' object has no attribute 'lower'

In [276]:
df.shape

(1257, 10)

In [277]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1257 entries, 0 to 1256
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1257 non-null   str
 1   company          1252 non-null   str
 2   address          1257 non-null   str
 3   experience       1257 non-null   str
 4   url              1257 non-null   str
 5   query            1257 non-null   str
 6   page             1257 non-null   int64
 7   vacancy_id       1257 non-null   str
 8   matched_queries  1257 non-null   object
 9   description      1250 non-null   str
dtypes: int64(1), object(1), str(8)
memory usage: 98.3+ KB

In [279]:
def extract_skills(description):

    if not isinstance(description, str):
        return []

    if not description.strip():
        return []

    text = description.lower()

    found_skills = []

    for skill, variants in SKILLS.items():

        for variant in variants:

            pattern = (
                r"(?<!\w)"
                + re.escape(variant.lower().strip())
                + r"(?!\w)"
            )

            if re.search(pattern, text):
                found_skills.append(skill)
                break

    return found_skills

In [280]:
df["skills"] = (
    df["description"]
    .apply(extract_skills)
)

In [281]:
df[
    [
        "title",
        "description",
        "skills"
    ]
].head(10)

,title,description,skills
0,Младший биоинформатик-аналитик,Обязанности: Анализ данных высокопроизводитель...,"[python, r, git]"
1,Data Ananlyst / Аналитик Данных,Мы – HR-холдинг Ventra. Уже более 22 лет мы сп...,"[python, power_bi, tableau, excel, sql, spark]"
2,Бизнес-аналитик,Аскона ищет бизнес- аналитика в команду продук...,[sql]
3,Системный аналитик (FinTech / Crypto / Blockch...,VeroTrace — платформа управления рисками при р...,"[sql, kafka, rest_api]"
4,Аналитик данных,Новая локация офиса: В ноябре переезжаем в нов...,"[python, tableau, sql]"
5,Специалист по управлению данными / Аналитик да...,Твои задачи: Работа с данными: Реализация шабл...,"[python, pandas, numpy, metabase, sql, airflow]"
6,Бэкенд-разработчик (java),Компания Липтсофт работает с 2012 года и заним...,"[java, postgresql, mongodb, redis, docker, kub..."
7,Аналитик данных (Power BI),Мы - продуктовая компания в сфере онлайн-развл...,"[python, power_bi, excel, sql, postgresql]"
8,Руководитель аналитики данных,Команда АЛЬФА-МОБАЙЛ это мобильный виртуальный...,"[python, power_bi, sql]"
9,Заместитель директора по маркетингу,"Сеть кафе-пекарен «Булочки», приглашает в свою...",[]

In [282]:
df[
    df["description"].isna()
][
    [
        "title",
        "company",
        "url"
    ]
]

,title,company,url
40,Менеджер проектов,Paper Planes,https://hh.ru/vacancy/136072352?query=Data+Ana...
289,Product Analyst,ООО Ок Софт,https://hh.ru/vacancy/135831324?query=BI+Analyst
901,"Менеджер (ИТ стратегия), Технологическая практика","Kept, Технологическая практика",https://hh.ru/vacancy/135206772?query=MLOps
971,ML Developer / Machine Learning Engineer,ИП Першина Маргарита Юрьевна,https://hh.ru/vacancy/136125248?query=AI+Engineer
995,Frontend Engineer (React / Next.js),Одно Поле,https://hh.ru/vacancy/135531047?query=AI+Engineer
1000,"Backend / Software Engineer (Python, FastAPI)",Одно Поле,https://hh.ru/vacancy/135531048?query=AI+Engineer
1151,Системный инженер,Хорошие сети,https://hh.ru/vacancy/136319514?query=Python+D...

In [283]:
df["skills_count"] = (
    df["skills"]
    .apply(len)
)

In [284]:
df[
    [
        "title",
        "query",
        "skills",
        "skills_count"
    ]
].head(20)

,title,query,skills,skills_count
0,Младший биоинформатик-аналитик,Data Analyst,"[python, r, git]",3
1,Data Ananlyst / Аналитик Данных,Data Analyst,"[python, power_bi, tableau, excel, sql, spark]",6
2,Бизнес-аналитик,Data Analyst,[sql],1
3,Системный аналитик (FinTech / Crypto / Blockch...,Data Analyst,"[sql, kafka, rest_api]",3
4,Аналитик данных,Data Analyst,"[python, tableau, sql]",3
5,Специалист по управлению данными / Аналитик да...,Data Analyst,"[python, pandas, numpy, metabase, sql, airflow]",6
6,Бэкенд-разработчик (java),Data Analyst,"[java, postgresql, mongodb, redis, docker, kub...",8
7,Аналитик данных (Power BI),Data Analyst,"[python, power_bi, excel, sql, postgresql]",5
8,Руководитель аналитики данных,Data Analyst,"[python, power_bi, sql]",3
9,Заместитель директора по маркетингу,Data Analyst,[],0
10,Бизнес-аналитик,Data Analyst,"[excel, sql, spark, hadoop, hive]",5
11,Системный аналитик Middle/Senior,Data Analyst,"[sql, postgresql, ms_sql_server, spark, kafka,...",8
12,Data Scientist,Data Analyst,"[python, pandas, numpy, statsmodels, plotly, p...",15
13,Product Manager в команду Core,Data Analyst,[],0
14,Финансовый директор (CFO),Data Analyst,[],0
15,Системный аналитик,Data Analyst,"[kafka, rest_api]",2
16,Руководитель отдела персонала (HRD/HRBP),Data Analyst,[],0
17,Бизнес-аналитик,Data Analyst,"[excel, sql, mysql, rest_api]",4
18,Инженер сопровождения,Data Analyst,"[python, pandas, sql, postgresql, airflow]",5
19,Java-разработчик,Data Analyst,"[java, postgresql, docker, kubernetes, git]",5

In [285]:
skill_columns = list(SKILLS.keys())

for skill in skill_columns:

    df[skill] = (
        df["skills"]
        .apply(
            lambda skills:
            int(skill in skills)
        )
    )

In [287]:
df.head()

,title,company,address,experience,url,query,page,vacancy_id,matched_queries,description,...,azure,gcp,fastapi,flask,django,rest_api,jupyter,notebook,sas,spss
0,Младший биоинформатик-аналитик,ООО Парсек Лаб,"Санкт-Петербург, р-н Приморский",Опыт 1-3 года,https://hh.ru/vacancy/135719646?query=Data+Ana...,Data Analyst,0,135719646,"[Data Analyst, Python Developer]",Обязанности: Анализ данных высокопроизводитель...,...,0,0,0,0,0,0,0,0,0,0
1,Data Ananlyst / Аналитик Данных,Ventra,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136031153?query=Data+Ana...,Data Analyst,0,136031153,"[BI Analyst, Data Analyst]",Мы – HR-холдинг Ventra. Уже более 22 лет мы сп...,...,0,0,0,0,0,0,0,0,0,0
2,Бизнес-аналитик,Группа Компаний «Аскона» | Логистика,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/136361346?query=Data+Ana...,Data Analyst,0,136361346,[Data Analyst],Аскона ищет бизнес- аналитика в команду продук...,...,0,0,0,0,0,0,0,0,0,0
3,Системный аналитик (FinTech / Crypto / Blockch...,ООО Веро Трейс,Москва,Опыт 3-6 лет,https://hh.ru/vacancy/135661700?query=Data+Ana...,Data Analyst,0,135661700,[Data Analyst],VeroTrace — платформа управления рисками при р...,...,0,0,0,0,0,1,0,0,0,0
4,Аналитик данных,RUTUBE,Москва,Опыт 1-3 года,https://hh.ru/vacancy/136365089?query=Data+Ana...,Data Analyst,0,136365089,[Data Analyst],Новая локация офиса: В ноябре переезжаем в нов...,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
skill_frequency = (
    df[skill_columns]
    .sum()
    .sort_values(ascending=False)
)

print(skill_frequency.head(30))

python          749
sql             580
docker          336
llm             294
postgresql      293
git             263
ci_cd           262
kubernetes      223
airflow         194
excel           183
pandas          170
rag             169
kafka           163
power_bi        160
clickhouse      137
fastapi         136
spark           134
pytorch         133
rest_api        120
gitlab          116
numpy           113
scikit_learn     99
tableau          99
nlp              97
redis            93
langchain        83
hadoop           77
mlflow           76
java             71
github           70
dtype: int64

In [ ]:
def inspect_skill(skill, n=10):
    sample = df[df[skill] == 1][
        [
            "title",
            "query",
            "skills",
            "description"
        ]
    ].head(n)

    return sample
display(inspect_skill("llm"))
display(inspect_skill("rag"))
display(inspect_skill("ci_cd"))
display(inspect_skill("spark"))
display(inspect_skill("git"))

,title,query,skills,description
29,ИИ специалист,Data Analyst,"[python, pandas, numpy, sql, scikit_learn, pyt...",AI/ML Engineer (Инженер искусственного интелле...
70,AI Engineer,Data Analyst,"[python, postgresql, redis, llm, rag, langchai...",Наш продукт — сервисы для премиальных клиентов...
80,"Python Developer AI team (в офис, г. Йошкар-Ола)",Data Analyst,"[python, llm, rag, langchain, airflow, dbt, ku...",TravelLine — единая платформа для автоматизаци...
152,Tech Lead / CTO — AI-стартап (динамическое цен...,Data Analyst,"[python, excel, sql, postgresql, llm, rag, doc...",Dyva AI — AI -ассистент управления ценой для д...
161,Руководитель группы разработки DWH / Team Lead...,Data Analyst,"[python, power_bi, sql, ms_sql_server, llm, ra...",Присоединяйся к команде крупнейшего пищевого п...
182,Бизнес - аналитик AI,Data Analyst,"[sql, llm, rag]",Обязанности: 1. Исследование и оценка AI-техно...
189,Менеджер проектов по внедрению ИИ,Data Analyst,"[python, excel, sql, nlp, llm, rag, docker, gi...",Обязанности: 1. Аудит и формирование гипотез: ...
335,AI Data Team Lead,BI Analyst,"[python, r, pandas, numpy, power_bi, tableau, ...","Location: Almaty, Kazakhstan Reports to: Direc..."
394,Стажер Data scientist,Data Scientist,"[python, nlp, huggingface, llm, rag, docker, g...","Ключевые задачи: Сбор, очистка и предобработка..."
402,Системный аналитик,Data Scientist,[rag],Мы ищем Fullstack аналитика для активного учас...

In [291]:
def show_skill_context(description, term, context=80):

    if not isinstance(description, str):
        return None

    text = description.lower()
    position = text.find(term.lower())

    if position == -1:
        return None

    start = max(0, position - context)
    end = min(len(description), position + len(term) + context)

    return description[start:end]




example = df[df["rag"] == 1].iloc[0]

print(
    show_skill_context(
        example["description"],
        "rag"
    )
)

low, WandB и др.); • Экспериментировать с LLM: fine-tuning, prompt engineering, RAG-архитектуры, интеграция через API (OpenAI, Anthropic, open-source модели); • Ра

In [292]:
skill_percent = (
    df[skill_columns]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(
    skill_percent.head(30).round(1)
)

python          59.6
sql             46.1
docker          26.7
llm             23.4
postgresql      23.3
git             20.9
ci_cd           20.8
kubernetes      17.7
airflow         15.4
excel           14.6
pandas          13.5
rag             13.4
kafka           13.0
power_bi        12.7
clickhouse      10.9
fastapi         10.8
spark           10.7
pytorch         10.6
rest_api         9.5
gitlab           9.2
numpy            9.0
scikit_learn     7.9
tableau          7.9
nlp              7.7
redis            7.4
langchain        6.6
hadoop           6.1
mlflow           6.0
java             5.6
github           5.6
dtype: float64

In [293]:
df.to_csv(
    "../data/processed/vacancies_with_skills.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
skill_frequency.to_csv(
    "../data/processed/skill_frequency.csv",
    encoding="utf-8-sig"
)